ROADMAP.md
=> roadmap-stub

example/lib/main.dart, lib/interface/JsonObject.dart, lib/model/Insight.dart, lib/model/Product.dart, lib/model/Product.g.dart, lib/model/ProductImage.dart, lib/model/RobotoffQuestion.dart, lib/model/SendImage.dart, lib/model/SpellingCorrections.dart, lib/model/User.dart, lib/openfoodfacts.dart, lib/utils/HttpHelper.dart, lib/utils/ImageHelper.dart, lib/utils/JsonHelper.dart, lib/utils/LanguageHelper.dart, lib/utils/ProductFields.dart, lib/utils/ProductHelper.dart, lib/utils/ProductQueryConfigurations.dart, lib/utils/ProductSearchQueryConfiguration.dart, test/api_test_getProduct.dart, test/api_test_getProductRaw.dart, test/api_test_getRobotoff.dart, test/api_test_postRobotoff.dart, test/api_test_saveProduct.dart, test/api_test_searchProducts.dart
- Support for more than 180 languages
- New query / search principle :
- In order to optimize the queries you can now set the return language and fields list through ProductQueryConfiguration (Default Behaviour)
- getProductRaw is still available (Old Behaviour)
=> Version 0.3

CHANGELOG.md, lib/model/Product.dart, lib/model/Product.g.dart, lib/utils/JsonHelper.dart, pubspec.yaml, test/api_test_getProduct.dart, test/api_test_getProductRaw.dart, test/api_test_saveProduct.dart
Introduced a new parsing method for servingQuantity
=> Fixed servingQuantity issue raised by 0.3.4

CHANGELOG.md, example/pubspec.lock, lib/model/Additives.dart, lib/model/Allergens.dart, lib/model/NutrientLevels.dart, lib/model/Product.dart, lib/model/Product.g.dart, lib/openfoodfacts.dart, lib/utils/PnnsGroupQueryConfiguration.dart, lib/utils/PnnsGroups.dart, pubspec.yaml, test/api_getProduct_test.dart, test/api_pnnsGroup2Query_test.dart
=> Added allergens and introduced PNNS groups and PnnsGroup2 queries

lib/model/Product.dart, lib/model/Product.g.dart, lib/utils/JsonHelper.dart, lib/utils/UnitHelper.dart, pubspec.lock, test/api_getProduct_test.dart
test fixed:
- api_getProduct_test
- api_searchProducts_test
field added for Product.dart 
- last modified_t
=> Some tests fixed and product attribute added

lib/model/Product.dart, lib/model/Product.g.dart, lib/openfoodfacts.dart, test/api_saveProduct_test.dart
- dont send a product name, if its null. (json includeIfNull=false)
- added test case for a product with a name in different languages
=> product name hotfix

README.md
Starting to document what is supported
=> Starting to document what is supported

lib/model/EcoscoreData.dart, lib/model/Product.dart, lib/model/Product.g.dart, test/json_product_generation_test.dart
=> fix: product JSON generation (EcoscoreData related)

lib/model/ProductImage.dart
Allows uploading packaging info / recycling instructions photos. Fixes #79
=> add packaging image type, fixes #79

lib/utils/ProductSearchQueryConfiguration.dart
I had forgotten to also add the cc parameter for ProductSearchQueryConfiguration (and not only ProductQueryConfiguration) when fixing #76.
=> add cc parameter to ProductSearchQueryConfiguration, #76

CHANGELOG.md, pubspec.yaml
Updated the changelog and bumped version number to 0.3.15 to publish on pub.dev
=> Publish release v0.3.15 to pub.dev

CHANGELOG.md, pubspec.yaml
=> publish v0.3.15+1 - release fix for #84

lib/openfoodfacts.dart, lib/utils/HttpHelper.dart, lib/utils/JsonHelper.dart, test/api_getProduct_test.dart, test/api_getRobotoff_test.dart, test/api_pnnsGroup2Query_test.dart, test/api_postRobotoff_test.dart, test/api_saveProduct_test.dart, test/api_searchProducts_test.dart
=> Improve test output

.github/workflows/test-sdk.yml
Closes #3
Example output: https://github.com/openfoodfacts/openfoodfacts-dart/actions/runs/541139242
=> Add Github action for testing the SDK

lib/model/EcoscoreAdjustments.dart, lib/model/EcoscoreAdjustments.g.dart, lib/model/EcoscoreData.dart, lib/model/EcoscoreData.g.dart, test/json_product_generation_test.dart
=> Fix EcoScoreData JSON generation

CHANGELOG.md, pubspec.yaml
I just released version 0.3.15+2 of the SDK
=> Prepare release of version 0.3.15+2

pubspec.yaml
These are the latest versions which are compatible with the current stable release of dart.
=> Update dependencies #98

CHANGELOG.md, pubspec.yaml
Let's see how many pub points we get with all your improvements. :)
=> Prepare release of v0.3.15+3

example/pubspec.yaml, pubspec.yaml
=> Dependency cleanup

README.md, lib/model/Ingredient.dart, lib/model/Product.dart, lib/model/ProductResult.dart, lib/model/SpellingCorrections.dart, lib/model/User.dart
=> Fix analysis errors

CHANGELOG.md, pubspec.yaml
I'd like to publish the new changes from the last 3 days, as some of them are needed for the "smoothie" app.
PR using the new image fields: https://github.com/openfoodfacts/smooth-app/pull/252
=> Prepare release of v1.0.2-beta

DOCUMENTATION.md, example/lib/main.dart, lib/model/SendImage.dart, lib/openfoodfacts.dart, test/api_addProductImage_test.dart, test/api_getProductRaw_test.dart, test/api_getProduct_test.dart, test/api_ocrIngredients_test.dart
Renaming SendImage.imageUrl -> SendImage.imageUri for #144
=> Rename SendImage.imageUrl -> SendImage.imageUri

lib/model/SendImage.dart
Fix for #149
All honours to @stephanegigandet :)
=> Add a language postfix to 'imagefield' of SendImage JSON

pubspec.yaml
=> Updated dependencies for pub.dev points

test/api_addProductImage_test.dart, test/api_getProductRaw_test.dart, test/api_getProduct_test.dart
Closes #146
This does not fix the actual problems with the tests, i.e. they test against something they change, but for what it is worth, it makes CI pass again.
=> fix: update expected test results.

lib/openfoodfacts.dart, test/api_getProduct_test.dart, test/api_searchProducts_test.dart
=> Replace '&quot;' with '"' (#162)

.github/workflows/dartdoc.yml, README.md
Deployed at (https://openfoodfacts.github.io/openfoodfacts-dart/)
=> Deploy Dartdocs using GitHub Actions

DOCUMENTATION.md, lib/model/Status.dart, lib/model/Status.g.dart, lib/model/User.dart, lib/model/User.g.dart, lib/openfoodfacts.dart, lib/utils/HttpHelper.dart, pubspec.yaml, test/test_constants.dart, test/user_management_test.dart
Fixes #133 
<details>
<summary>Web form, Pro, Newsletter</summary>
> ------WebKitFormBoundaryyHDyruIaIK0NghVQ
> Content-Disposition: form-data; name="name"
> 
> DasIstMeinName
> ------WebKitFormBoundaryyHDyruIaIK0NghVQ
> Content-Disposition: form-data; name="email"
> 
> meineEmail@gmail.com
> ------WebKitFormBoundaryyHDyruIaIK0NghVQ
> Content-Disposition: form-data; name="userid"
> 
> dasistmeinnutzername
> ------WebKitFormBoundaryyHDyruIaIK0NghVQ
> Content-Disposition: form-data; name="password"
> 
> Pass
> ------WebKitFormBoundaryyHDyruIaIK0NghVQ
> Content-Disposition: form-data; name="confirm_password"
> 
> Pass
> ------WebKitFormBoundaryyHDyruIaIK0NghVQ
> Content-Disposition: form-data; name="pro"
> 
> on
> ------WebKitFormBoundaryyHDyruIaIK0NghVQ
> Content-Disposition: form-data; …
=> Add support for user creation

CHANGELOG.md, pubspec.yaml
=> docs: prepare release of version 1.2.0 of the SDK

lib/openfoodfacts.dart, test/api_getProduct_test.dart
* `api_getProduct_test.dart`: added tests around the new method
* `openfoodfacts.dart`: created method `getEcoscoreHtmlDescription`
=> feature/#155 - new method "OpenFoodAPIClient.getEcoscoreHtmlDescription"

lib/model/Nutriments.dart, lib/model/Nutriments.g.dart, lib/utils/UnitHelper.dart, test/api_getProduct_test.dart
1. pantothenic-acid
1. biotin
1. chloride
1. chromium
1. fluoride
1. iodine
1. manganese
1. molybdenum
1. omega-3-fat
1. omega-6-fat
1. trans-fat
* `Nutriments.dart`: added 11 nutrients
* `Nutriments.g.dart` (generated)
=> feature/#166 - added several nutrients

lib/model/parameter/ContainsAdditives.dart, lib/model/parameter/WithoutAdditives.dart, test/api_searchProducts_test.dart
New file:
* `WithoutAdditives.dart`: "Without Additives" search API parameter
* `api_searchProducts_test.dart`: replaced `ContainsAdditives` with `WithoutAdditives`
* `ContainsAdditives.dart`: deprecated in favor of new class `WithoutAdditives`
=> feature/#194 - explicit parameter WithoutAdditives replaces ContainsAdditives

lib/utils/InvalidBarcodes.dart, test/api_getProduct_test.dart
New file:
* `InvalidBarcodes.dart`: Invalid barcode blacklist
=> feature/#188 - new class InvalidBarcodes

CHANGELOG.md, pubspec.yaml
=> docs: prepare release of version 1.3.0 of the SDK

.github/workflows/dartdoc.yml
Removed unexpected input 'GITHUB_TOKEN' in dartdoc Generation workflow.
=> Removed dartdoc generation workflow warning

lib/model/Product.g.dart, lib/utils/LanguageHelper.dart, test/product_from_json_test.dart
Test to reproduce #201
Unfortunately no solution yet.
=> Test to reproduce fromJson bug #201

lib/model/Product.dart, test/api_saveProduct_test.dart, test/product_from_json_test.dart
fixes #201 in a different way (complementary I think) than https://github.com/openfoodfacts/openfoodfacts-dart/pull/202/commits/05da4bb66e114b60a29b3690c66251c08b2e3436
=> Make toJson use the same format as the server for in_languages fields

lib/model/Product.dart, lib/model/parameter/ContainsAdditives.dart, lib/model/parameter/OutputFormat.dart, lib/model/parameter/SearchSimple.dart, lib/openfoodfacts.dart, lib/utils/AbstractQueryConfiguration.dart, lib/utils/PnnsGroupQueryConfiguration.dart, lib/utils/ProductHelper.dart
* `AbstractQueryConfiguration.dart`
* `ContainsAdditives.dart`
* `openfoodfacts.dart`
* `OutputFormat.dart`
* `PnnsQueryGroupConfiguration.dart`
* `Product.dart`
* `ProductHelper.dart`
* `SearchSimple.dart`
=> feature/#204 - Refactor all the @deprecated with an explicit message

CHANGELOG.md, pubspec.yaml
Hopefully this time it will completely fix #201
=> docs: prepare release of version 1.3.2 of the SDK

lib/model/Nutriments.dart, lib/model/Nutriments.g.dart, lib/utils/UnitHelper.dart, test/api_getProduct_test.dart, test/api_saveProduct_test.dart
=> Fix write API for nutrient fields

lib/utils/AbstractQueryConfiguration.dart, lib/utils/OpenFoodAPIConfiguration.dart
=> Added globalLanguages and globalCC to OpenFoodAPIConfiguration 

CHANGELOG.md
@peterwvj, I added the last PR from @monsieurtanuki and have rearranged a little bit. Since the tests are only failing because of the test server I would say we can release the new version.  
Feel free to merge this pull request
=> Release 1.3.3 

test/api_addProductImage_test.dart, test/api_getProductRaw_test.dart, test/api_getProduct_test.dart, test/api_get_autocompleted_suggestions_test.dart, test/api_searchProducts_test.dart, test/test_constants.dart
Changes that make the tests pass
=> fix: test assertions

lib/model/Status.dart, lib/openfoodfacts.dart, test/api_saveProduct_test.dart, test/api_searchProducts_test.dart
Fixes #247 and gets the tests to pass.
=> Improve error message when saving products using invalid user

CHANGELOG.md, lib/utils/AbstractQueryConfiguration.dart, pubspec.yaml, test/api_getProductRaw_test.dart, test/api_getProduct_test.dart, test/knowledge_panels_from_json_test.dart
A bit of code clean up included :)
=> Prepare release of 1.3.5

lib/model/Product.dart, lib/utils/ProductFields.dart, test/api_getProduct_test.dart, test/api_saveProduct_test.dart
* `Product.dart`: added a dedicated field and its computing method
* `ProductFields.dart`: added a dedicated field belonging to the "in languages" category
* `api_getProduct_test.dart`: added a dedicated test
=> feature/#104 - support for the new "Image Refresh" API

lib/model/Product.dart
Impacted file:
* `Product.dart`
=> feature_2/#191 - added eco-score and nutri-score categories (ProductImprovement)

lib/model/KnowledgePanel.g.dart, lib/model/KnowledgePanelElement.g.dart
changes to generated files were missed
=> Add changes that were missed in #294

lib/model/KnowledgePanel.dart, lib/model/KnowledgePanel.g.dart, lib/model/KnowledgePanelElement.g.dart, lib/model/Product.g.dart
And rerun json parser generator
Before:
After:
=> fix: parsing of Grade Json field

.github/workflows/dartdoc.yml, .github/workflows/release.yml, CHANGELOG.md, pubspec.yaml
Finally working release workflow + changelog order fix
Finally closes: #225
=> fix: Release workflow

lib/openfoodfacts.dart, lib/utils/HttpHelper.dart
Removed many useless UserAgent from OpenFoodAPIClient methods and moved them to the one place where they are used.
=> style: Removed unnecessary appearances

.github/labeler.yml, .github/workflows/label.yml
- Start PR labelling automation
- the label on this PR has been itself auto-added.
- #218
=> Start PR labelling automation

lib/model/EcoscoreData.g.dart, lib/model/KnowledgePanel.g.dart, lib/model/KnowledgePanelElement.g.dart, lib/model/Product.dart, lib/model/Product.g.dart, lib/model/RobotoffQuestion.g.dart, lib/utils/HttpHelper.dart, pubspec.yaml
* `EcoscoreData.g.dart`: slightly different generated code
* `HttpHelper.dart`: removed useless import
* `KnowledgePanel.g.dart`: slightly different generated code
* `KnowledgePanelElement.g.dart`: slightly different generated code
* `Product.dart`: removed useless import
* `Product.g.dart`: slightly different generated code
* `pubspec.yaml`: upgraded dependencies, including json and analyzer
* `RobotoffQuestion.g.dart`: slightly different generated code
=> build: pubspec dependencies refresh

lib/model/Nutriments.dart, lib/model/Nutriments.g.dart, test/api_saveProduct_test.dart
* `api_saveProduct_test.dart`: added vitamin B12 + unit to a "save and check" test
* `Nutriments.dart`: added `toJson: UnitHelper.unitToString` to most `Unit`s, that only had `fromJson: UnitHelper.stringToUnit`
* `Nutriments.g.dart`: generated file
=> fix: #357 - added forgotten "toJson: UnitHelper.unitToString"s (tons of them!)

.github/CODEOWNERS
- Add CODEOWNERS for PR reviews
=> ci: Add CODEOWNERS for PR reviews

.github/dependabot.yml
=> Make dependabot semantic

.github/workflows/semantic-pr.yml
Add an action to check for semantic PRs titles
=> ci: Add an action to check for semantic PRs titles

README.md
- Updating the README with some of the latest features
=> doc: Updating with some of the latest features

lib/utils/ProductHelper.dart
Impacted file:
* `ProductHelper.dart`: removed deprecated method `addTranslatedFields`
=> refactor: removed 1-year-old deprecated method

test/api_saveProduct_test.dart
Just to keep in mind it should be fixed - one day.
Impacted file:
* `api_saveProduct_test.dart`
cf. https://github.com/openfoodfacts/smooth-app/pull/1142
=> test: added disabled test about nutrition

lib/openfoodfacts.dart, lib/utils/TaxonomyQueryConfiguration.dart, lib/utils/UriHelper.dart
- migrating all the get requests to post
(Insert a screenshot to provide visual record of your changes, if visible)
- #354 and #414 
- #407 
(please be as granular as possible)
=> fix: #414 -  changed get request to post

lib/model/Nutriments.dart, lib/model/Nutriments.g.dart
fix: #241 Added "energy-kj"
- #241 
- #241
=> fix: #241 Added "energy-kj"

lib/openfoodfacts.dart, lib/utils/HttpHelper.dart
=> fix: send user credentials in POST requests

.github/workflows/github-projects.yml
-  auto add new issues to gh projects
=> ci: auto add new issues to gh projects

README.md
=> feat: README.md with a list of known apps using the SDK

README.md, lib/openfoodfacts.dart, test/user_management_test.dart
A username may not exceed 20 characters
#441
=> feat: Username max length

lib/utils/JsonHelper.dart, test/api_searchProducts_test.dart
- fixes: #440 
`JsonHelper.imagesFromJson` failed when the coordinates are `400` (as int) and not `full
`
``` 
E/flutter ( 7340): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'int' is not a subtype of type 'String?'
E/flutter ( 7340): #0      JsonHelper.imagesFromJson
package:openfoodfacts/utils/JsonHelper.dart:86
```
=> fix: coordinates_image_size is no subtype of String

.gitignore, lib/model/Attribute.dart, test/api_getProduct_test.dart
- Exposing to Attribute related panelID
- https://github.com/openfoodfacts/smooth-app/issues/1029
=> feat: Expose to Attribute related panelID

.github/workflows/auto-assign-pr.yml
=> ci: autoassign PR

.github/workflows/release.yml
- The autorelease is currently broken `line 1: pub: command not found`
=> fix: Auto release

lib/model/KnowledgePanelElement.dart, lib/model/KnowledgePanelElement.g.dart, test/api_saveProduct_test.dart
* `api_saveProduct_test.dart`: unrelated test skip
* `KnowlegdePanelElement.dart`: `title` is now optional
* `KnowlegdePanelElement.g.dart`: generated
- Title is now optional in knowledge panel element
- #477
=> fix: #477 - title is now optional in knowledge panel element

lib/utils/HttpHelper.dart
add user agent parameters:
app_platform = userAgent.system
comment = combined string 
- #482
=> fix: #482 add user agent parameters

example/pubspec.yaml, pubspec.yaml
- upgrade dependencies
There are 3 tests that fail, but they also fail on “main”.
=> chore: upgrade dependencies

test/api_getProduct_test.dart
- Just trying to fix the unit tests
- I don't think unit tests can pass the very first time the way they're currently built (possible collision of the same tests run from different servers), but I believe at least we can make them work the second time.
=> chore: unit tests

lib/utils/ProductListQueryConfiguration.dart
Impacted file:
* `ProductListQueryConfiguration.dart`: API v2 for multi barcode search
- API v2 for multi barcode search
- #516
=> feat: #516 - API v2 for multi barcode search

.github/workflows/auto-assign-pr.yml, lib/model/parameter/SortBy.dart, test/api_searchProducts_test.dart
* `SortBy.dart`: added ECOSCORE sort by option
* `api_searchProducts_test.dart`: added a test comparing the product orders generated by all sort options
- added ECOSCORE sort by option
- Closes #517
=> feat: #517 - added ECOSCORE and NUTRISCORE sort-by options

.github/workflows/test-sdk.yml
- Run the tests daily at 0 and 12 o'clock
- Closes: #478
=> ci: Run sdk tests daily (twice)

lib/openfoodfacts.dart
- The `login` method didn't return a correct result.
- A test was added to make it "more correct".
- It's better but not very safe - other implementations should be used instead (on the server side too?)
- https://github.com/openfoodfacts/smooth-app/issues/2784
=> fix: login

pubspec.yaml
- feat: add funding links
- I do [what Flutter influencers tell me to do](https://youtu.be/1DP35xRo84s?t=400)
=> feat: add funding links

.github/ISSUE_TEMPLATE/feature_request.md
- ci: pr-template-harmonization
=> ci: pr-template-harmonization

.github/ISSUE_TEMPLATE/bug_report.md
=> ci: improve bug template

lib/model/LoginStatus.dart, lib/openfoodfacts.dart, test/api_getProduct_test.dart, test/api_searchProducts_test.dart, test/user_management_test_prod.dart, test/user_management_test_test_env.dart
New file:
* `LoginStatus.dart`: Status after an attempt to log in.
* `api_getProduct_test.dart`: unrelated typo fix
* `openfoodfacts.dart`: new method `login2` that returns a `LoginStatus`
* `user_management_test_prod.dart`: now uses `login2` instead of `login`
* `user_management_test_test_env.dart`: now uses `login2` instead of `login`
- New method `login2` that returns data about user
- Closes #579
=> feat: #579 - new method to log in, that returns data about user

test/api_addProductImage_test.dart, test/api_events_test.dart, test/api_folksonomy_test.dart, test/api_getProduct_test.dart, test/api_getTaxonomyAdditivesServer_test.dart, test/api_getTaxonomyAllergensServer_test.dart, test/api_getTaxonomyCountriesServer_test.dart, test/api_getTaxonomyIngredientsServer_test.dart, test/api_getTaxonomyPackagingsServer_test.dart, test/api_getToBeCompletedProducts_test.dart, test/api_getUserProducts_test.dart, test/api_get_autocompleted_suggestions_test.dart, test/api_ocrIngredients_test.dart, test/api_saveProduct_test.dart, test/api_searchProducts_test.dart, test/ordered_nutrient_test.dart
Fixes new infos in the dart analyzer: [no_leading_underscores_for_local_identifiers](https://dart-lang.github.io/linter/lints/no_leading_underscores_for_local_identifiers.html)
=> style: no_leading_underscores_for_local_identifiers

README.md
=> fix: Fix Badges

README.md
- docs: link-to-new-openapi-doc
=> docs: link-to-new-openapi-doc

LICENSE
Impacted file:
* `LICENSE`: updated the copyright year
- Now it's 2023!
- And that would trigger a new version.
- #643
=> fix: 643 - updated the copyright year in the LICENSE

README.md, lib/src/open_food_api_client.dart
Fixed docs for getting contribution data about a user
=> fix: docs for user data query

lib/openfoodfacts.dart, lib/src/open_food_api_client.dart, lib/src/robot_off_api_client.dart, lib/src/robotoff_api_client.dart
- Deprecated and routed the robotoff apis to a new file for decluttering
- Changed names of some APIs to maintain consistency in new file
- No breaking changes for now
- #714 
- #339
=> fix: Refactor Robotoff methods

lib/src/model/insight.dart, test/api_get_product_test.dart, test/api_get_to_be_completed_products_test.dart
- Gentle refactoring of `InsightAnnotation` with a good `enum` syntax.
=> fix: "InsightAnnotation" with better enum syntax

lib/src/utils/image_helper.dart
Some refactoring: in Smoothie we had to duplicate some code from off-dart just because it was private. Now it's made public.
* `image_helper.dart`: new method `getBarcodeSubPath`; new `root` parameter
=> fix: ImageHelper refactoring

lib/src/model/product.dart, lib/src/model/product.g.dart, lib/src/model/product_result.g.dart, lib/src/utils/json_helper.dart, pubspec.yaml, test/issue752_test.dart
Fixes #752
After adding the proposed fix, I did run into some issues regenerating the *.g.dart files using build_runner but I managed to fix that by upgrading the SDK dependencies according to the instructions described [here](https://github.com/dart-lang/build/issues/3519#issuecomment-1587514460).
=> fix: issue with JSON conversion of packagings data

pubspec.yaml
- Upgrade of sdk and http dependency versions, related to dart 3 upgrade.
- Fixes: #764
- Fixes: #735
=> fix: 764 - upgraded sdk and http dependency

.github/workflows/github-projects.yml
- ci: GH projects for packaging issues
=> ci: GH projects for packaging issues

lib/src/open_food_api_client.dart
Hi everyone,
There is a small typo in the `resetPassword` method.
The email is sent… but the Dart package thinks that's an error
=> fix: password reset not working

test/api_get_taxonomy_ingredients_server_test.dart, test/api_get_to_be_completed_products_test.dart, test/api_search_products_test.dart
- Minor fixes about unit tests that rely on actual data. The data changed, we slightly change our tested values.
=> fix: unit test values

lib/src/open_food_api_client.dart, lib/src/robot_off_api_client.dart, test/api_get_robotoff_test.dart
- Impact from https://github.com/openfoodfacts/robotoff/issues/1143 - we needed to readjust our parameters for Robotoff.
- #742
* `api_get_robotoff_test.dart`: minor refactoring
* `open_food_api_client.dart`: removed a deprecated method
* `robot_off_api_client.dart`: new robotoff syntax - replaced country with countries
=> fix!: 742 - robotoff - countries instead of country

lib/src/model/parameter/allergens_parameter.dart, lib/src/model/parameter/states_tags_parameter.dart, lib/src/model/sign_up_status.dart, lib/src/personalized_search/available_preference_importances.dart, lib/src/utils/product_query_configurations.dart, lib/src/utils/product_search_query_configuration.dart, pubspec.yaml
- Just an upgrade to lints 3.0.0, which lead to insignificant changes but to fixing a big fat bug too.
=> chore: upgrade to lints 3.0.0

pubspec.yaml
=> doc: add pubspec topics

.github/workflows/test-sdk.yml
=> ci: downgrade codecov

.github/labeler.yml
=> ci: emojis + more entries

.github/labeler.yml
=> ci: image labeler

test/api_not_food_get_product_test.dart
- Fixed the open beauty test, with a more relevant barcode.
- This is currently the only failing test, so with this guy merged everything passes.
=> chore: fixed open beauty test

test/api_get_taxonomy_packaging_recycling_server_test.dart
- Had to update expected values for one unit test.
=> fix: unit test with updated expected values

LICENSE
- Updated the LICENSE to 2024.
- #643
=> chore: LICENSE 2024

test/api_get_product_test.dart, test/api_search_test.dart
- Unit tests failed, which called for minor changes to expected values.
- _En passant_, the tests are now performed in PROD env, and not in TEST env anymore.
=> fix: unit tests about autocomplete

test/api_folksonomy_test.dart
- Unit tests fail: data needed to be changed.
=> chore: unit tests data change

test/api_get_robotoff_test.dart
- Unit tests data change for Robotoff
=> chore: unit tests data change (robotoff)

lib/src/model/product.dart, lib/src/model/product.g.dart, lib/src/utils/product_fields.dart, test/api_get_product_test.dart
- New product field `'expiration_date'`
- Fixes: #895
- https://github.com/openfoodfacts/smooth-app/issues/5127
* `api_get_product_test.dart`: added test for new product field about `'expiration_date'`
* `product.dart`: added product field for `'expiration_date'`
* `product_fields.dart`: added product field for `'expiration_date'`
=> feat: 895 - added product field `'expiration_date'`

.github/labeler.yml
- fix: new format for the labeler
=> fix: new format for the labeler

.github/labeler.yml
=> fix: auth label

lib/src/model/login_status.dart, lib/src/model/user.dart, lib/src/open_food_api_client.dart, lib/src/utils/http_helper.dart
Hi everyone!
Some requests require to be authenticated via a cookie.
That's why, this PR allows to get it during the login and send it later
=> feat: Allow to receive a cookie and send it later

lib/src/utils/product_query_configurations.dart
Hi everyone!
I'm sorry, I've forgotten to commit a file in the previous PR.
But everything will be OK after:
=> fix: Cookie -> one missing param

README.md
=> fix: trigger release please

.github/workflows/test-sdk.yml
=> ci: typo in test-sdk.yml

lib/src/model/user.dart, test/user_management_test_prod.dart
- Added a link to add a discussion topic on the OpenFoodFacts wiki page of a user.
- Closes: #962
* `user.dart`: added method `getUserWikiDiscussionPage`
* `user_management_test_prod.dart`: tested new method `getUserWikiDiscussionPage`
=> feat: 962 - link to add a discussion topic on the wiki

.github/workflows/top-issues.yml
- Allow users to upvote issues and create associated top issues dashboard
=> ci: top issues

.github/labeler.yml
- ci: Folksonomy engine labeler
=> ci: Folksonomy engine labeler

.github/workflows/github-projects.yml
- Add dispatcher for Open Beauty, Pet Food, Products
=> ci: Update github-projects.yml

.github/workflows/github-projects.yml
- dispatcher to track releases across OFF
=> ci: dispatcher to track releases across OFF

lib/src/model/old_product_result.g.dart
- Minor fix of lint warnings
- Fixes: #1007
=> fix: 1007 - no more lint warnings

.github/ISSUE_TEMPLATE/feature_request.md
- ci: Update feature_request.md
=> ci: Update feature_request.md

lib/src/model/product.dart, lib/src/model/product.g.dart, lib/src/utils/product_fields.dart, test/api_get_product_test.dart
This PR allows to get all data quality tags
=> feat: added product fields 'data_quality_{*_}tags'

lib/src/model/product.g.dart, test/api_get_product_test.dart
- There is a bug in #1033, and here is the fix.
- Minor test bug fixed too
=> chore: fixed 1033 and a minor test bug

lib/src/open_prices_api_client.dart, test/api_prices_test.dart
- Added `getUserProfile` method to fetch user data from Open Prices API and return it as `PriceUser` model.
- This will be used in User Dashboard in order to replicate [Dashboard page - OpenFoodFacts](https://prices.openfoodfacts.org/dashboard)
- https://github.com/openfoodfacts/smooth-app/issues/5206
- Supports PR https://github.com/openfoodfacts/smooth-app/pull/6559
=> feat: Added Get user data function OpenPricesAPIClient

.github/labeler.yml
- ci: Add new file patterns to labeler configuration
=> ci: Add new file patterns to labeler configuration
