openfoodfacts/openfoodfacts-dart

lib/model/SearchResult.dart
lib/model/SearchResult.g.dart
lib/openfoodfacts.dart

Hi,
First of all: I really like this project 😄 
I was trying to perform a search using `OpenFoodAPIClient.searchProducts` and saw that I got several parsing errors. This PR aims to solve that.
I tried the modifications locally and it worked as expected:
- the API gives back JSON
- there's no parsing error anymore when parsing `{ ..., "count": "49", ... }`

Fix searching errors

---

README.md

The "addProductImage" tests assume that the working directory is the `test` folder.

Fix test instructions in the README

---

lib/model/Nutriments.dart
lib/model/Nutriments.g.dart

Hello,
I made the changes to include the `kcal` information into the Nutriment class.
It has been discussed in issue #44 
I am not familiar with OpenFoodFacts, so I am not sure if I used the good fields: `energy-kcal_100g` vs `energy-kcal`...
All tests passe, except for one:
```
00:02 +15 -1: ~/openfoodfacts-dart/test/api_getProductRaw_test.dart: OpenFoodAPIClient get raw products get product test 1 [E]                                                                                                                           
Expected: <15>
Actual: <18>
package:test_api                                   expect
package:flutter_test/src/widget_tester.dart 348:3  expect
test/api_getProductRaw_test.dart 37:7              main.<fn>.<fn>
```
However, this one seems to be broken on master too. …

Add kcal values in Nutriments

---

lib/model/Status.dart
lib/model/Status.g.dart

Apparently the `imageId` is sometimes returned as a `String` so it's safer to parse it rather than casting it.

Fix parsing of imageId

---

example/pubspec.lock
lib/model/Product.dart
lib/model/Product.g.dart
pubspec.lock
pubspec.yaml
test/api_saveProduct_test.dart

Hey guys :)
Christoph(cjk) reported yesterday via #general in slack the following issue:
> a few products I participated in were edited today by user grumpf ((app)Dart API - TIOLI), however it appears the app or API does put invalid data into the Serving size attribute (they are all "null" now)
I can confirm the issue. 
a null value or string "null" will be written, if no serving size attibute has been set.
I dismissed the idea to load ALL attributes before saving the product.
Instead I changed the json mapping to remove the attribute "serving_size" if it is null. This is the common way, we process other attributes, too.
`@JsonKey(name: 'serving_size', includeIfNull: false)
String servingSize;`
I extended the test case in _api_saveProduct_test.dart_ to check if the servingSize attribute …

don't send NULL attributes via json 

---

lib/model/Product.dart
lib/model/Product.g.dart
lib/utils/ProductFields.dart
test/api_getProduct_test.dart

Hi,
I have added the ecoscore_grade field to Product, which is currently only available when we query with ecoscore_alpha.
Adding this will allows apps (like the smooth app) to prepare the arrival of the ecoscore (which I'm really excited about).
If this is accepted, I will try to add ecoscore_data handling later.

added field ecoscore_grade to product

---

lib/openfoodfacts.dart

Allows passing a null value for the user, to upload product photos without an OFF account.
fixes #72

allow anonymous photo upload

---

lib/utils/ProductQueryConfigurations.dart

This is to allow app to pass directly the country code and language code parameters in the cc and lc fields.
It would probably be a good thing to add an OpenFoodFactsCountry helper, similar to the OpenFoodFactsLanguage helper.
I'd like to refactor the OpenFoodFactsLanguage with a map first, to replace the switch statement and the for loop to get the language corresponding to a code.

allow setting the country code cc field, #76

---

analysis_options.yaml
example/lib/main.dart
lib/interface/JsonObject.dart
lib/model/Additives.dart
lib/model/Allergens.dart
lib/model/EnvironmentImpactLevels.dart
lib/model/IngredientsAnalysisTags.dart
lib/model/Insight.dart
lib/model/NutrientLevels.dart
lib/model/RecommendedDailyIntake.dart
lib/model/RobotoffQuestion.dart
lib/model/SendImage.dart
lib/model/parameter/SearchSimple.dart
lib/model/parameter/TagFilter.dart
lib/openfoodfacts.dart
lib/utils/HttpHelper.dart
lib/utils/JsonHelper.dart
lib/utils/NutrimentsHelper.dart
lib/utils/PnnsGroupQueryConfiguration.dart
lib/utils/ProductQueryConfigurations.dart
lib/utils/ProductSearchQueryConfiguration.dart
pubspec.lock
pubspec.yaml
test/api_addProductImage_test.dart
test/api_getProduct_test.dart
test/api_getRobotoff_test.dart
test/api_ocrIngredients_test.dart
test/test_constants.dart

* `analysis_options.yaml`: added a reference to `pedantic`, with limits
* `pubspec.yaml`: added a reference to `pedantic: ^1.9.2` for code analysis
* tons of `dart` files: minor fixes in order to match the coding rules

fix/#90 - matching the coding rules in order to get a better pub.dev score

---

lib/utils/HttpHelper.dart
lib/utils/UriReader.dart
lib/utils/UriReader_io.dart
lib/utils/UriReader_js.dart
lib/utils/UriReader_stub.dart

Web is now supported!
New files:
* `UriReader.dart`: Abstract reader of URI data, declined in "not web" and "web" versions
* `UriReader_io.dart`: Reader of URI data, "not web" version (i.e. supports `File`)
* `UriReader_js.dart`: Reader of URI data, "web" version
* `UriReader_stub.dart`: Needed for conditional imports
Impacted file:
* `HttpHelper.dart`: now using a UriReader

fix/#90_2 - +10 points - conditional imports for "not web" and "web" apps

---

lib/utils/UriReader.dart
test/api_addProductImage_test.dart
test/api_getProduct_test.dart
test/api_ocrIngredients_test.dart

* `api_addProductImage_test.dart`: `File`s are now relative
* `api_getProduct_test.dart`: `File`s are now relative
* `api_ocrIngredients_test.dart`: `File`s are now relative
* `UriReader.dart`: now support relative `File`s

fix_3/#90 - support of relative files in UriReader

---

lib/model/Product.dart
lib/model/SearchResult.dart
lib/model/SearchResult.g.dart
lib/openfoodfacts.dart
lib/utils/ProductHelper.dart

* `openfoodfacts.dart`: removed any reference to translated fields, that are now automatically computed
* `Product.dart`: automatically computed the translated categories and labels
* `ProductHelper.dart`: deprecated the method to translate fields, which is automatic now
* `SearchResult.dart`: removed the confusing and space-consuming raw `jsonProducts` field; let the `fromJson` method point to the json annotation generated method
* `SearchResult.g.dart`: removed the confusing and space-consuming raw `jsonProducts` field

fix_4/#90 - better space management and code readability for SearchResult

---

lib/utils/HttpHelper.dart
pubspec.yaml

Upgraded all the dependencies. The only one not supporting null safety is `build_runner `(dev_dependencies)
We have 7x `'nullable' is deprecated and shouldn't be used. Has no effect. (deprecated_member_use at [openfoodfacts] lib\model\Ingredient.dart:12` in the `@JsonKey()`. I left them in, for clearity when switching to null safety

Upgraded dependencies

---

CHANGELOG.md
lib/openfoodfacts.dart
pubspec.yaml

Post null safety migration fix.

API should not require a user being passed when searching products

---

lib/model/Ingredient.dart
lib/model/Ingredient.g.dart
test/api_getProduct_test.dart

Adding 'vegan', 'vegetarian' and 'fromPalmOil' fields to the Ingredient class (for #125).
At first I wanted to use existing enums in `IngredientsAnalysisTags`, but they seem to be not very suitable for the purpose:
- They don't have an `ignore` value and it doesn't make sense for them to have such a value (e.g. a product cannot have an "ignore" vegan status).
- I would have to create 6 distinct `toJson` and `fromJson` functions for 3 distinct enums, which is a lot of boilerplate code.

Add 'vegan', 'vegetarian' and 'fromPalmOil' fields to the Ingredient class

---

lib/model/ProductImage.dart
lib/model/SendImage.dart
lib/openfoodfacts.dart
lib/utils/HttpHelper.dart
test/api_addProductImage_test.dart

Fixes #134:
````
2021-03-14 21:58:10.234 3827-4274/org.openfoodfacts.app E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Null check operator used on a null value
#0      HttpHelper.doMultipartRequest (package:openfoodfacts/utils/HttpHelper.dart:66:65)
<asynchronous suspension>
#1      OpenFoodAPIClient.addProductImage (package:openfoodfacts/openfoodfacts.dart:108:12)
<asynchronous suspension>
#2      _ImageUploadCardState._getImage (package:smooth_app/cards/data_cards/image_upload_card.dart:77:13)
<asynchronous suspension>
````
I think it's related to null safety, specifically it was this that was problematic:
`````
for (MapEntry<String?, Uri?> entry in files.entries) {
List<int> fileBytes = await UriReader.instance!.readAsBytes(entry.value);
`````
I changed …

fix image upload, fixes #134

---

lib/personalized_search/matched_product.dart

We need to differentiate products that we know do not match preferences from products that may or may not match preferences (products for which we don't have enough data to compute a known value for an attribute selected by the user).

3 values for MatchedProduct status: yes, no, unknown (instead of bool)

---

.github/workflows/test-sdk.yml
README.md
example/lib/main.dart
example/pubspec.yaml
pubspec.yaml
test/api_addProductImage_test.dart
test/api_getProductRaw_test.dart
test/api_getProduct_test.dart
test/api_getRobotoff_test.dart
test/api_ocrIngredients_test.dart
test/api_pnnsGroup2Query_test.dart
test/api_postRobotoff_test.dart
test/api_saveProduct_test.dart
test/api_searchProducts_test.dart
test/json_product_generation_test.dart
test/recommended_daily_intake_test.dart

@teolemon mentioned on [slack](https://openfoodfacts.slack.com/archives/CC668J8AC/p1617001176000200) that a official Dart setup action got release. 
Because we used `flutter_test` for testing, this packages was a flutter package. I switched to the official [dart test package](https://pub.dev/packages/test) and updated the ci workflow. This should now be a flutter + dart package.

switched to dart

---

CHANGELOG.md
pubspec.yaml

The enum values for IngredientsAnalysisTags have changed, so it is a breaking change, this is why I bumped the middle version number.
While we are doing breaking changes, I think we should include a fix for #144 as well.

Prepare release of v1.1.0-beta (include breaking changes)

---

example/pubspec.yaml

The `example` subproject currently has `openfoodfacts: ^1.0.2-beta` as its dependency, which breaks its compilation since the latest openfoodfacts is `^1.1.0-beta`.
Seems that the example project should rather depend on the most up to date code, which is always stored in its parent folder.
This way no one will ever forget to change a version in its pubspec.yaml.

Make the example subproject to depend on the parent folder

---

lib/model/Product.dart
lib/model/Product.g.dart
lib/openfoodfacts.dart
lib/utils/ProductFields.dart
lib/utils/ProductHelper.dart
lib/utils/ProductQueryConfigurations.dart
lib/utils/ProductSearchQueryConfiguration.dart
test/api_getProduct_test.dart

Adding more translated product fields for #151
- Added several `Translated`-fields to Product.
- Marked the `de`, `en` and `fr` fields as deprecated because now (almost`*`) same functionality is available by the `translated` fields.
`*` - "almost" - because now to get a product name in 3 those language the SDK user has to make 3 requests. If that's an issue - the `deprecated` annotation can of course be removed.
- Many fields of Product are reordered so that related fields would be declared close to each other.
- Product's constructor received new arguments it didn't have before for some reason.
- `Product.toJson` now fills translated fields when they're specified
- Product got a new method - `toValidatedData`, it's used instead of `toData` when a product is sent to the server, and it …

Add multiple '_translated' fields to Product

---

lib/model/EcoscoreData.dart
lib/model/EcoscoreData.g.dart
test/api_getProductRaw_test.dart
test/api_getProduct_test.dart

I have added the agribalyse field to Product.ecoscoreData.
The Agribalyse class was already existing (but unused) and currently only include the score.

feat: add agribalyse score to EcoscoreData

---

lib/interface/JsonObject.dart
lib/model/EcoscoreData.dart
lib/model/EcoscoreData.g.dart
test/api_getProduct_test.dart

I have added the support for the `missing_data_warning` field, which allows the user to know the ecoscore may be improved.
However, I have decided to use a non-nullable boolean field, while the returned json use a `1` or empty value. I'm not sure why the server does not use boolean values but I believe it should be simplified here.

feat: add EcoscoreData.missingDataWarning field support

---

DOCUMENTATION.md
lib/openfoodfacts.dart
pubspec.yaml

For #159 
@stephanegigandet with my own login data it worked perfectly but with the dart test user it did not (of course on the test server), is this api available on there, is the dart test user already inside it? This would be interesting for tests

Login via the auth.pl api

---

README.md
example/lib/main.dart
lib/model/Product.dart
lib/openfoodfacts.dart
lib/utils/TagType.dart
test/api_get_autocompleted_suggestions_test.dart
test/api_suggestion_test.dart

@teolemon I am not sure how to handle the packager codes. 
It always give the same result example: 
https://world.openfoodfacts.org/cgi/suggest.pl?lc=en&tagtype=emb_codes&EM
https://world.openfoodfacts.org/cgi/suggest.pl?lc=en&tagtype=emb_codes&EMS
https://world.openfoodfacts.org/cgi/suggest.pl?lc=en&tagtype=emb_codes&string=EH
https://world.openfoodfacts.org/cgi/suggest.pl?lc=en&tagtype=emb_codes&string=rgf
It always return: 
["BE 1-05 EC","BE 1-11 EC","BE 1-17 EC","BE 1-18 EC","BE 1-21 EC","BE 1-23 EC","BE 1-26 EC","BE 1-28 EC","BE 1-28-H EC","BE 1-31 EC","BE 1-38 EC","BE 1-39 EC","BE 1-42 EC","BE 1 EC","BE 10-09-2008 EC","BE 100783 EC","BE 100811 EC","BE 100904 EC","BE 100926 EC","BE 100939 EC","BE 100960 EC","BE 100963 EC","BE 101070 EC","BE 101082-H EC","BE 101202-H EC"]

#131 : Adding suggestion to the SDK

---

lib/interface/Parameter.dart
lib/model/parameter/ContainsAdditives.dart
lib/model/parameter/OutputFormat.dart
lib/model/parameter/Page.dart
lib/model/parameter/PageSize.dart
lib/model/parameter/SearchSimple.dart
lib/model/parameter/SearchTerms.dart
lib/model/parameter/SortBy.dart
lib/model/parameter/TagFilter.dart
lib/utils/ProductSearchQueryConfiguration.dart

On the way to a 130/130 pub.dev score...
By the way @teolemon @stephanegigandet: what's the purpose of `search_type=1` or `search_type=0` in the search API URI?
* `ContainsAdditives.dart`: added a comment on class; refactored as non-nullable
* `OutputFormat.dart`: added a comment on class and enum; refactored
* `Page.dart`: added a comment on class; refactored as non-nullable
* `PageSize.dart`: added a comment on class; refactored as non-nullable
* `Parameter.dart`: added a comment on class; created method `addToMap`
* `ProductSearchQueryConfiguration.dart`: added a comment on class; refactored some fields as non-nullable
* `SearchSimple.dart`: not done much as the purpose of the class is unclear
* `SearchTerms.dart`: added a comment on class; refactored as non-nullable
* …

fix_5/#90 - added comments to Parameter-related classes

---

lib/model/parameter/OutputFormat.dart
lib/model/parameter/SearchSimple.dart
lib/openfoodfacts.dart
lib/utils/PnnsGroupQueryConfiguration.dart
lib/utils/ProductSearchQueryConfiguration.dart
test/api_searchProducts_test.dart

* `api_searchProducts_test.dart`: removed all references to `OutputFormat` and `SearchSimple`
* `OutputFormat.dart`: deprecated because in fact always JSON
* `ProductSearchQueryConfiguration.dart`: explicit JSON output
* `SearchSimple.dart`: deprecated because useless

feature/#107 - deprecated useless parameters OutputFormat and SearchSimple

---

lib/utils/ImageHelper.dart
lib/utils/JsonHelper.dart
lib/utils/LanguageHelper.dart
lib/utils/NutrimentsHelper.dart
lib/utils/PnnsGroupQueryConfiguration.dart
lib/utils/PnnsGroups.dart
lib/utils/ProductFields.dart
lib/utils/ProductHelper.dart
lib/utils/QueryType.dart
lib/utils/UnitHelper.dart

There are still classes to add comments to in this folder, but this is a quick PR.
* `ImageHelper.dart`
* `JsonHelper.dart`
* `LanguageHelper.dart`
* `NutrimentsHelper.dart`
* `PnnsGroupQueryConfiguration.dart`
* `PnnsGroups.dart`
* `ProductFields.dart`
* `ProductHelper.dart`
* `QueryType.dart`
* `UnitHelper.dart`

fix_6/#90 - added comments to classes and methods in folder "utils"

---

lib/openfoodfacts.dart
test/api_saveProduct_test.dart

* `api_saveProduct_test.dart`: new test "confirm that nutrient fields are saved"
* `openfoodfacts.dart`: fixed the way nutrient API parameters are set

fix/#48 - now saving nutrients

---

lib/model/parameter/ContainsAdditives.dart
test/api_searchProducts_test.dart

* `api_searchProducts_test.dart`: uncommented test "search products by keywords" with a less verbose keyword; fixed test "search products filter additives" with a less verbose keyword
* `ContainsAdditives`: added a comment about the probable bad naming of parameter "filter"

fix/#189 - simplified time-out prone search products tests

---

DOCUMENTATION.md
lib/interface/JsonObject.dart
lib/model/Product.dart
lib/model/Product.g.dart
lib/openfoodfacts.dart
lib/utils/AbstractQueryConfiguration.dart
lib/utils/LanguageHelper.dart
lib/utils/ProductFields.dart
lib/utils/ProductHelper.dart
lib/utils/ProductListQueryConfiguration.dart
lib/utils/ProductQueryConfigurations.dart
lib/utils/ProductSearchQueryConfiguration.dart
test/api_getProduct_test.dart
test/api_saveProduct_test.dart
test/api_searchProducts_test.dart

Adding ability to request and set multiple translated product fields at once.
If some user of an OFF-based application knows multiple languages (e.g. English and German), it might be very useful for the user to be able to request and see a product fields translated into several languages.
For example, a product might have its name set in English but have a German ingredients list (no English ingredients list).
When a user requests such a product and the request's language is set to English, the user won't see ingredients list.
But if the user did let the app know they also know German language and the app would request the product with both English and German translation, then the user would get much more comprehensive data - both name and ingredients list of the product.
This pull …

Add ability to request and set multiple translated product fields at once

---

CHANGELOG.md
pubspec.yaml

This is to fix issue #201 that prevents saving a product to JSON and reading it back.

docs: prepare release of version 1.3.1 of the SDK

---

.github/workflows/test-sdk.yml

https://github.com/openfoodfacts/openfoodfacts-dart/pull/228#issuecomment-920039780
> I think thats (the test failing) because they both run at the same time and this sometimes causes conflicts on the test server, running them one after the other should fix it

Dublicate ci workflow run fix

---

CHANGELOG.md
lib/utils/UnitHelper.dart
pubspec.yaml

Please check whether the CHANGELOG properly reflects recent changes

Release 1.3.3

---

lib/model/Product.dart
test/api_getProduct_test.dart

* `api_getProduct_test.dart`: added checks for `getProductImprovements`
* `Product.dart`: create `enum ProductImprovement` and `Product.getProductImprovements()`

feature/#191 - added and computed possible product improvements

---

lib/model/TaxonomyCategory.dart
lib/model/TaxonomyIngredient.dart
lib/model/TaxonomyLabel.dart
lib/utils/TaxonomyQueryConfiguration.dart
test/api_getTaxonomyCategories_test.dart
test/api_getTaxonomyIngredients_test.dart
test/api_getTaxonomyLabels_test.dart

This adds parameters to the Taxonomy queries that have hierarchies (Category, Ingredient, Label) that allow fetching of the root entries of the taxonomy (the entries without parents).

Add queries to get the roots from the server

---

.github/workflows/release.yml

To avoid confusion that we release on every commit

CD: Renamed workflow

---

lib/model/TaxonomyAdditive.dart
lib/model/TaxonomyAllergen.dart
lib/model/TaxonomyCategory.dart
lib/model/TaxonomyCountry.dart
lib/model/TaxonomyIngredient.dart
lib/model/TaxonomyLabel.dart
lib/model/TaxonomyLanguage.dart
lib/openfoodfacts.dart
lib/utils/AbstractQueryConfiguration.dart
lib/utils/CountryHelper.dart
lib/utils/OpenFoodAPIConfiguration.dart
lib/utils/ProductListQueryConfiguration.dart
lib/utils/ProductQueryConfigurations.dart
lib/utils/ProductSearchQueryConfiguration.dart
lib/utils/TaxonomyQueryConfiguration.dart
test/api_getProduct_test.dart
test/api_getTaxonomyAdditives_test.dart
test/api_getTaxonomyAllergens_test.dart
test/api_getTaxonomyCategories_test.dart
test/api_getTaxonomyCountries_test.dart
test/api_getTaxonomyIngredients_test.dart
test/api_getTaxonomyLabels_test.dart
test/api_getTaxonomyLanguages_test.dart
test/api_getTaxonomy_test.dart

New file:
* `CountryHelper.dart`: country enums and their ISO-2-codes
* `AbstractQueryConfiguration.dart`: deprecated `String? cc` in favor of `OpenFoodFactsCountry? country`
* `api_getTaxonomy_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `api_getTaxonomyAdditives_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `api_getTaxonomyAllergens_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `api_getTaxonomyCategories_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `api_getTaxonomyCountries_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `api_getTaxonomyIngredients_test.dart`: now using `OpenFoodAPIConfiguration.globalCountry`
* `api_getTaxonomyLabels_test.dart`: now using …

feat: #233 - new class OpenFoodFactsCountry, clearer than "cc"

---

lib/openfoodfacts.dart
lib/utils/CountryHelper.dart
lib/utils/UriHelper.dart
test/api_getProduct_test.dart
test/api_saveProduct_test.dart

* `api_getProduct_test.dart`: new test "get product uri"
* `CountryHelper.dart`: replaced 'gb' with the OFF standard 'uk'
* `openfoodfacts.dart`: new method `getProductUri`
* `UriHelper.dart`: new method `replaceSubdomain`

feat: #301 - new method getProductUri

---

lib/model/parameter/TagFilter.dart
test/api_searchProducts_test.dart

* `api_searchProduct_test.dart`: additional tests on all `TagFilterType`s; refactoring
* `TagFilter.dart`: added more explicit `enum TagFilterType` as filter types

feat: #307 - added 21 enum values for advanced search parameters

---

lib/model/ProductImage.dart
lib/openfoodfacts.dart
test/api_addProductImage_test.dart

* `api_addProductImage_test.dart`: new test about "unselect product image"
* `openfoodfacts.dart`: new method `unselectProductImage`
* `ProductImage.dart`: minor unrelated refactoring

feat: #306 - unselect product image

---

lib/folksonomy.dart
lib/model/KeyStats.dart
lib/model/KeyStats.g.dart
lib/model/ProductList.dart
lib/model/ProductList.g.dart
lib/model/ProductStats.dart
lib/model/ProductStats.g.dart
lib/model/ProductTag.dart
lib/model/ProductTag.g.dart
lib/openfoodfacts.dart
lib/utils/HttpHelper.dart
lib/utils/JsonHelper.dart
lib/utils/OpenFoodAPIConfiguration.dart
lib/utils/UriHelper.dart
test/api_folksonomy_test.dart
test/api_saveProduct_test.dart

New files:
* `api_folksonomy_test.dart`: Tests around folksonomy
* `folksonomy.dart`: Client calls of the Folksonomy API (Open Food Facts)
* `KeyStats.dart`: Folksonomy: statistics around a tag key.
* `ProductList.dart`: Folksonomy: current value for a product and a tag key.
* `ProductStats.dart`: Folksonomy: statistics about the tag keys on a product.
* `ProductTag.dart`: Folksonomy product tag: for this barcode, that value is set for that key.
* `HttpHelper.dart`: added "delete" and "put" requests
* `JsonHelper.dart`: added a helper method around timestamps
* `OpenFoodAPIConfiguration.dart`: added reference URIs for folksonomy
* `openfoodfacts.dart`: exported folksonomy files
* `UriHelper.dart`: added a helper method for folksonomy URIs

feat: #158 - introduction to folksonomy

---

lib/utils/CountryHelper.dart
test/api_saveProduct_test.dart

Impacted file:
* `CountryHelper.dart`: lowercased the country code for conversions

fix: Lowercased country code

---

lib/model/ProductFreshness.dart
lib/openfoodfacts.dart
test/api_searchProducts_test.dart

New file:
* `ProductFreshness.dart`: Freshness of a [Product].
* `api_searchProduct_test.dart`: new test about "product freshness"
* `openfoodfacts.dart`: new method `getProductFreshness`

feat: #350 - new method getProductFreshness

---

lib/openfoodfacts.dart
test/ordered_nutrient_test.dart

The point (for apps) is to retrieve that string, store it locally, and refresh it from the API when relevant (and not systematically).
* `openfoodfacts.dart`: new method `getOrderedNutrientsJsonString`; refactored `getOrderedNutrients`
* `ordered_nutrient_test.dart`: added test for new method `getOrderedNutrientsJsonString`

feat: new method "getOrderedNutrientsJsonString"

---

lib/utils/TaxonomyQueryConfiguration.dart
test/api_getTaxonomy_test.dart
test/api_searchProducts_test.dart

The taxonomy API changed from specifying the type of taxonomy using "type" to using "tagtype".  This reflects that change in the query configurations.

Switch from 'type' to 'tagtype' in the taxonomy API

---

lib/model/Ingredient.dart
lib/model/Ingredient.g.dart
lib/model/KnowledgePanels.dart
lib/model/Product.dart
lib/model/Product.g.dart
lib/openfoodfacts.dart
lib/utils/ProductFields.dart
lib/utils/ProductQueryConfigurations.dart
test/api_getProduct_test.dart

* `api_getProduct_test.dart`: refactored the ecoscore html test; added a knowledge panels test; added a group in order to test ingredients in API version V0 and V2
* `Ingredient.dart`: added optional fields `percentEstimate` and `ingredients`
* `Ingredient.g.dart`: generated
* `KnowledgePanels.dart`: added static methods in order to be considered as a `Product` field
* `openfoodfacts.dart`: new method `getProductString`, used from methods `getProductRaw`, `getProduct` and now deprecated methods  `getEcoscoreHtmlDescription`, `getKnowledgePanels`
* `Product.dart`: added optional fields `knowledgePanels` and `environmentInfoCard`
* `ProductFields.dart`: added fields about `knowledgePanels` and `environmentInfoCard`
* …

feat: new method getProductString, api V0 and V2, new product and ingredient fields

---

lib/openfoodfacts.dart
lib/utils/UriHelper.dart
test/api_getProduct_test.dart

@teolemon the URI does not work for EMB_CODES
* `api_getProduct_test.dart`: tests for new methods `getTaxonomyTranslationUri` and `getCrowdinUri`
* `openfoodfacts.dart`: new methods `getTaxonomyTranslationUri` and `getCrowdinUri`

feat: #348 - new methods getTaxonomyTranslationUri and getCrowdinUri

---

lib/openfoodfacts.dart
lib/utils/HttpHelper.dart
lib/utils/UriHelper.dart
test/configuration_test.dart

* `configuration_test.dart`: added test for user agent; refactored
* `HttpHelper.dart`: new method `addUserAgentParameters`, automatically used for post and multipart requests
* `openfoodfacts.dart`: added `addUserAgentParameters: false` for specific `getUri` calls like post and multipart
* `UriHelper.dart`: new parameter `addUserAgentParameters` for `getUri`

feat: #370 - added app_name and app_version to http queries (as parameters)

---

lib/utils/HttpHelper.dart
lib/utils/OpenFoodAPIConfiguration.dart
pubspec.yaml
test/configuration_test.dart

* `configuration_test.dart`: added tests with "uuid"
* `HttpHelper.dart`: included new static `uuid` to parameters
* `OpenFoodAPIConfiguration.dart`: added `static String? uuid`
* `pubspec.yaml`: unrelated upgrade

feat: #370 - added "uuid" to configuration

---

lib/utils/TagType.dart
test/api_get_autocompleted_suggestions_test.dart

* `api_get_autocompleted_suggestions_test.dart`: added a test about packaging
* `TagType.dart`: added a "packaging" tag type
- with the new "packaging" tag type, `getAutocompletedSuggestions` can be called for packaging.

feat: #382 - added a "packaging" tag type

---

lib/model/Product.dart
test/api_getProductRaw_test.dart
test/api_getProduct_test.dart
test/api_saveProduct_test.dart
test/api_searchProducts_test.dart

* `api_getProduct_test.dart`: fixed a value because of new packaging algo
* `api_getProductRaw_test.dart`: fixed a value that slightly changed
* `api_saveProduct_test.dart`: fixed a value because of new packaging algo
* `api_searchProducts_test.dart`: specific test for packaging filter; refactored
* `Product.dart`: fixed an ambiguous way of coding (that used to work, strangely)
The idea is to have successful (and reliable) unit tests.

fix: successful unit tests

---

lib/model/Nutriments.dart

Impacted file:
* `Nutriments.dart`: added the set of nutrient ids supported by `Nutriments`.
To be used when another source of nutrients (e.g. `OrderedNutrient`) has a broader list of nutrients - that we simply could not handle with `Nutriments`.

feat: added the set of nutrient ids supported by Nutriments.

---

lib/events.dart
lib/model/BadgeBase.dart
lib/model/BadgeBase.g.dart
lib/model/EventCreate.dart
lib/model/EventCreate.g.dart
lib/model/EventsBase.dart
lib/model/EventsBase.g.dart
lib/model/LeaderboardEntry.dart
lib/model/LeaderboardEntry.g.dart
lib/openfoodfacts.dart
lib/utils/JsonHelper.dart
lib/utils/OpenFoodAPIConfiguration.dart
lib/utils/UriHelper.dart
test/api_events_test.dart

Still missing: couldn't test how to create an event. Are we talking about the same users as in the "official OpenFoodFacts" API? (aka "off off"). Good news is that the TEST env works - which is not the case for Folksonomy.
New files:
* `api_events_test.dart`: Tests around Events API.
* `BadgeBase.dart`: Events API: badge.
* `BadgeBase.g.dart`: generated
* `EventCreate.dart`: Events API: event create.
* `EventCreate.g.dart`: generated
* `events.dart`: Client calls of the Events API (Open Food Facts).
* `EventsBase.dart`: Events API: event.
* `EventsBase.g.dart`: generated
* `LeaderboardEntry.dart`: Events API: leaderboard entry.
* `LeaderboardEntry.g.dart`: generated
* `JsonHelper.dart`: added a nullable timestamp conversion method.
* `OpenFoodAPIConfiguration.dart`: added …

feat: #349 - added support for Events API

---

lib/model/TaxonomyPackaging.dart
lib/model/TaxonomyPackaging.g.dart
lib/openfoodfacts.dart
test/api_getTaxonomyPackagingsServer_test.dart

New files:
* `api_getTaxonomyPackagingsServer_test.dart`: Integration test about packagings.
* `TaxonomyPackaging.dart`: A JSON-serializable version of a Packaging taxonomy result.
* `TaxonomyPackaging.g.dart`: generated
Impacted file:
* `openfoodfacts.dart`: new method `getTaxonomyPackagings`; exported new class `TaxonomyPackaging`
- first step towards a potential "download the whole tree" method for selected taxonomies
- in the meanwhile, `TaxonomyPackaging` did not exist before and deserved to be created

feat: #401 - added packaging taxonomy

---

CHANGELOG.md

Impacted file:
* `CHANGELOG.md`: moved version 1.9.1 to the correct position

fix: changelog order

---

lib/model/KnowledgePanelElement.dart
lib/model/KnowledgePanelElement.g.dart
test/knowledge_panels_from_json_test.dart

PR related to issue #408
I have included the different fields within the `KnowledgePanelTextElement` class.
I was wondering if a dedicated class like `KnowledgePanelTextElementSource` wouldn't be better in that case.
However, it would force us to create a dedicated parser/serializer.
What would you think about this?

feat: Support for source fields in the Knowledge panel API

---

lib/model/Product.g.dart
lib/model/TaxonomyCountry.dart
lib/model/TaxonomyCountry.g.dart
lib/utils/LanguageHelper.dart
test/api_getTaxonomyCountriesServer_test.dart
test/api_getTaxonomyCountries_test.dart

* `api_getTaxonomyCountries_test.dart`: refactored with the simplified fields
* `api_getTaxonomyCountriesServer_test.dart`: refactored with the simplified fields
* `LanguageHelper.dart`: added a language; added 3 json-decode helpers methods
* `TaxonomyCountry.dart`: added 2 fields; simplified constructor; simplified fields; removed useless `toJson` methods
* `TaxonomyCountry.g.dart`: generated
- the structure of TaxonomyCountry evolved
- `parents` and `children` eventually do not mean anything
- new fields `synonyms` and `wikidata`
- ISO codes obviously should not depend on input languages
- https://github.com/openfoodfacts/openfoodfacts-dart/issues/410

feat: #410 - refactored TaxonomyCountry with simplified fields

---

lib/openfoodfacts.dart
lib/utils/ProductListQueryConfiguration.dart
test/api_searchProducts_test.dart

* `api_searchProducts_test.dart`: additional test; refactored
* `openfoodfacts.dart`: changed method `getProductList` from GET to POST
* `ProductListQueryConfiguration.dart`: overrode `getParametersMap` in order to add barcodes as POST parameters
- GET has limits (number of characters), POST doesn't.
- For getProductList, there are potentially tons of parameters (the barcodes), therefore we had to play it safe and to switch from GET to POST
- #407

fix: #407 - getProductList now works with unlimited number of barcodes

---

lib/openfoodfacts.dart
lib/utils/AbstractQueryConfiguration.dart
lib/utils/PnnsGroupQueryConfiguration.dart
lib/utils/ProductListQueryConfiguration.dart
lib/utils/ProductQueryConfigurations.dart
lib/utils/ProductSearchQueryConfiguration.dart

* `AbstractQueryConfiguration.dart`: added abstract protected method `getUriPath` and method `getResponse`
* `openfoodfacts.dart`: using new method `AbstractQueryConfiguration.getResponse`
* `PnnsGroupQueryConfiguration.dart`: implemented new method `getUriPath`
* `ProductListQueryConfiguration.dart`: implemented new method `getUriPath`
* `ProductQueryConfigurations.dart`: implemented new method `getUriPath`
* `ProductSearchQueryConfiguration.dart`: implemented new method `getUriPath`
- simple additional refactoring after #415

refactor: #414 - refactored query configuration methods

---

lib/utils/ImageHelper.dart
lib/utils/OpenFoodAPIConfiguration.dart
test/api_addProductImage_test.dart

Related to #232 
The current image upload test does not update an image, because the product already has it. This PR uses a random barcode so that we can actually upload the image.

fix: actually upload an image on a random product

---

test/api_getProductRaw_test.dart

Impacted file:
* `api_getProductRaw_test.dart`: getting cleaner data from PROD; more lenient tests
- PR tests were failing because of data change on one product
- This PR slightly changed the tests, in order to pass

fix: getProductRaw tests

---

.github/workflows/github-projects.yml

- Disable when token is not there

ci: Disable Add to GitHub Projects on forks

---

README.md
lib/utils/BarcodesValidator.dart
test/barcode_validator_test.dart

OFF only accepts EAN8 and EAN13 barcodes.
This PR allows to check if a barcode is valid.
My implementation is freely based on https://commons.apache.org/proper/commons-validator/, to allow potential evolutions.
To check if a barcode is valid, just call `BarcodeValidator.isValid("1234")`.
Will fix #439

feat: Barcodes validation for EAN8 & EAN13

---

lib/model/Product.dart
lib/model/Product.g.dart
lib/utils/JsonHelper.dart
pubspec.yaml

* `Product.dart`: removed a 1 year old deprecated field
* `pubspec.yaml`: upgraded
- `Product` field `imgSmallUrl` has been deprecated for one year; it's fair to remove it now altogether.
- unrelated `pubspec.yaml` upgrade
[Edit: removed an unrelated file change]

fix: Removed deprecated Product field imgSmallUrl

---

lib/model/parameter/Page.dart
lib/model/parameter/PageNumber.dart
lib/openfoodfacts.dart
lib/utils/ProductListQueryConfiguration.dart
test/api_searchProducts_test.dart

New file:
* `PageNumber.dart`: "Page number" search API parameter.
* `api_searchProducts_test.dart`: now using `PageNumber` instead of deprecated `Page`
* `openfoodfacts.dart`: exports new class `PageNumber`
* `Page.dart`: deprecated in favor of less ambiguous new class `PageNumber`
* `ProductListQueryConfiguration.dart`: now using `PageNumber` instead of deprecated `Page`
- in #447 a developer had issues with a class named "Page" being in both openfoodfacts AND in `material.dart`
- there are ways to deal with that kind of issues, but it's fair to prevent bad interactions with capital packages like `material.dart`
- the solution was to create a new class with a less common name (`PageNumber`) and to deprecate the old one (`Page`)
- #447

fix: #447 - new class "PageNumber" replacing  ambiguous "Page" parameter

---

lib/openfoodfacts.dart

Impacted file:
* `openfoodfacts.dart`: removed irrelevant `postInsightAnnotation` default value for `QueryType`
- While reviewing a smoothie PR (https://github.com/openfoodfacts/smooth-app/pull/1352), I noticed an inconsistency in the way we handled `QueryType` parameters in `openfoodfacts.dart`'s methods.
- I fixed that inconsistency.
- https://github.com/openfoodfacts/smooth-app/pull/1352

fix: postInsightAnnotation - consistency for QueryType parameter

---

lib/personalized_search/matched_product_v2.dart
lib/personalized_search/product_preferences_manager.dart
test/api_getProduct_test.dart
test/api_matchedProductV1_test.dart
test/api_matchedProductV2_test.dart
test/api_productPreferences_test.dart
test/api_saveProduct_test.dart
test/api_searchProducts_test.dart

New files:
* `api_matchedProductV1_test.dart`: Tests around Matched Product v1.
* `api_matchedProductV2_test.dart`: Tests around Matched Product v2.
* `api_productPreferences_test.dart`: Tests around Product Preferences. (unrelated)
* `matched_product_v2.dart`: Match and score of a `Product` vs. Preferences, v2.
* `api_getProduct_test.dart`: refactored moving code to new file `api_matchedProductV1_test.dart`
* `api_searchProducts_test.dart`: unrelated minor refactoring
* `product_preferences_manager.dart`: unrelated new method `getAttributeIdsWithImportance`
- Implementation of the V2 of `MatchedProduct`
- #466

feat: #466 - matched product v2

---

lib/utils/HttpHelper.dart

- The author is currently not honored for fixes since we send the whole object not just the user id

fix: Just send user id in from header

---

lib/openfoodfacts.dart
test/api_getProduct_test.dart
test/api_getToBeCompletedProducts_test.dart
test/api_getUserProducts_test.dart
test/api_matchedProductV2_test.dart
test/api_saveProduct_test.dart
test/api_searchProducts_test.dart

* `api_getProduct_test.dart`: added a timeout to a unit test
* `api_getToBeCompletedProducts_test.dart`: no longer using a now deprecated method
* `api_getUserProducts_test.dart`: no longer using a now deprecated method
* `api_matchedProductV2_test.dart`: no longer using a now deprecated method
* `api_saveProduct_test.dart`: flagged as "skip" a problematic unit test
* `api_searchProducts_test.dart`: no longer using a now deprecated method
* `openfoodfacts.dart`: refactored method `searchProducts` to the detriment of now deprecated methods `getProducts` and `getProductList`
- While working on API v2, I noticed similarities in code that could be solved through refactoring.
- I also "fixed" a test (longer timeout duration)

fix: deprecated search methods in favor of searchProducts

---

lib/model/IngredientsAnalysisTags.dart
lib/model/parameter/IngredientsAnalysisParameter.dart
test/api_searchProducts_test.dart

New file:
* `IngredientsAnalysisParameter.dart`: Ingredients Analysis search API parameter.
* `api_searchProducts_test.dart`: added tests related to new parameter `IngredientsAnalysisParameter`
* `IngredientsAnalysisTags.dart`: refactored with `extension`, needed for reusability.
- Now we have a new parameter, in order to restrict ingredients analysis tags
- E.g. vegan(yes/no/maybe/unknown), vegetarian(yes/no/maybe/unknown), palm oil free (yes/no/maybe/unknown)
- The parameters can be combined. One test is even checking that if a product is "not vegetarian", then it cannot be (yes/maybe/unknown) for vegan (as it must be "not vegan").
- Closes #524

feat: #524 - added ingredients analysis tags (vegan, vegetarian, palm oil free)

---

lib/model/State.dart
lib/model/parameter/StatesTagsParameter.dart
test/api_searchProducts_test.dart

New files:
* `State.dart`: States of a `Product`. To be used in search API, with `StatesTagsParameter`.
* `StatesTagsParameter.dart`: States Tags as completed or to-be-completed. Filter combo mode is 'AND'.
Impacted file:
* `api_searchProducts_test.dart`: added a group of tests around the new parameter `StatesTagsParameter`
- New `StatesTagsParameter` search filter.
- Based on new `State` `enum`, that lists the possible states. For each state, you'll have to say if it's completed or to-be-completed.
- #531

feat: #531 - new StatesTagsParameter search filter

---

.github/workflows/auto-assign-pr.yml
lib/model/Allergens.dart
lib/model/parameter/AllergensParameter.dart
test/api_searchProducts_test.dart

New file:
* `AllergensParameter.dart`: List of allergens to filter in and out. Filter combo mode is 'AND'.
* `Allergens.dart`: added `AllergensTag` for the 14 main allergens.
* `api_searchProducts_test.dart`: added a group and 5 tests around the new `AllergensParameter` API parameter.
- New class `AllergensParameter` for the search API.
- With that we can restrict to products with and/or without allergens among the 14 main allergens.
- #526

feat: #526 - new AllergensParameter search filter

---

lib/model/parameter/AllergensParameter.dart
lib/model/parameter/BarcodeParameter.dart
lib/model/parameter/Barcodes.dart
lib/model/parameter/BoolMapParameter.dart
lib/model/parameter/StatesTagsParameter.dart
lib/openfoodfacts.dart
lib/utils/ProductListQueryConfiguration.dart
lib/utils/ToBeCompletedConfiguration.dart
test/api_getProduct_test.dart
test/api_getToBeCompletedProducts_test.dart
test/api_matchedProductV2_test.dart
test/api_searchProducts_test.dart

New files:
* `Barcodes.dart`: "Barcodes" search API parameter.
* `BoolMapParameter.dart`: Abstract map of `bool` as `Parameter`.
* `AllergensParameter.dart`: refactored as `BoolMapParameter<AllergensTag>`
* `api_getToBeCompletedProducts_test.dart`: minor refactoring around a deprecated class
* `api_matchedProductV2_test.dart`: minor refactoring around a deprecated class
* `api_searchProducts_test.dart`: fixed test duration; refactoring
* `openfoodfacts.dart`: minor refactoring around a deprecated class
* `ProductListQueryConfiguration.dart`: deprecated
* `StatesTagsParameter.dart`: refactored as `BoolMapParameter<State>`
* `ToBeCompletedConfiguration.dart`: deprecated
- New `Barcodes` search parameter
- Deprecated both `ToBeCompletedConfiguration` and …

feat: new "Barcodes" parameter; deprecated configurations

---

lib/model/KnowledgePanelElement.g.dart
lib/model/Product.dart
lib/model/Product.g.dart
lib/model/TaxonomyCountry.g.dart
lib/utils/ProductFields.dart
test/api_getProduct_test.dart

* `api_getProduct_test.dart`: added tests on new field `Product.novaGroup`; unrelated - refactored tests with `expect` instead of `assert`
* `KnowledgePanelElement.g.dart`: unrelated, generated
* `Product.dart`: added field `novaGroup`
* `ProductFields.dart`: added field `NOVA_GROUP`
* `TaxonomyCountry.g.dart`: unrelated, generated
- New product field `novaGroup`, directly accessible instead of using `Nutriments.novaGroup` or attributes.

feat: new field Product.novaGroup

---

lib/utils/ImageHelper.dart

Impacted file:
* `ImageHelper.dart`: deprecated methods that we have no added-value about; fixed a method that wouldn't work on Windows
- It's been a long time since I noticed that we used package `image` for nothing.
- I've deprecated its usage, as it's not what the package is all about.
- I've also fixed an incorrect usage of `path`.

fix: imageHelper - minor fix about Windows; deprecated methods

---

lib/model/Nutriments.dart
lib/model/Nutriments.g.dart
lib/model/Product.dart
lib/model/Product.g.dart
test/api_getProduct_test.dart
test/api_getRobotoff_test.dart
test/api_saveProduct_test.dart

* `api_getProduct_test.dart`: switched one test to prod; minor refactoring
* `api_getRobotoff_test.dart`: switched one test to prod
* `api_saveProduct_test.dart`: minor refactoring
* `Nutriments.dart`: added fields `'energy-kcal_serving'`, `'energy-kj_100g'` and `'energy-kj_serving'`
* `Nutriments.g.dart`: generated
* `Product.dart`: added field `'nutrition_data'`; minor refactoring
- Added fields to `Product` and `Nutriments` that we definitely need.
- Fixes #565

fix: #565 - added 'nutrition_data' flag and energy fields

---

lib/openfoodfacts.dart
test/api_getRobotoff_test.dart

* `api_getRobotoff_test.dart`: added a test for "no `'insight_types'`"; refactored
* `openfoodfacts.dart`: potentially no `'insight_types'` in `getRandomRobotoffQuestion`
- We needed to be able not to specify insight types  in `getRandomRobotoffQuestion`
- Closes #573
- https://github.com/openfoodfacts/smooth-app/pull/3102

feat: #573 - getRandomRobotoffQuestion with optional insight types

---

lib/model/KnowledgePanelElement.dart
lib/model/KnowledgePanelElement.g.dart
test/api_getProduct_test.dart
test/api_getRobotoff_test.dart
test/api_saveProduct_test.dart
test/api_searchProducts_test.dart

* `KnowledgePanelElement.dart`: minor fix on `KnowledgePanelPanelGroupElement`
* `KnowledgePanelElement.g.dart`: generated
- The way it was coded, `KnowledgePanelPanelGroupElement` were supposed to have a mandatory `'title'`.
- This afternoon, that was not always the case in TEST env (https://fr.openfoodfacts.net/api/v2/product/3270160717323?fields=knowledge_panels): 
```json
"panel_group_element": {
"panel_ids": ["nutrition_facts_table"]
}
```
- As a side effect, the product could not be downloaded.
- The PR is about making the title optional.
- What I can say about PROD is that for the same product, `'title'` is always populated (https://fr.openfoodfacts.orgapi/v2/product/3270160717323?fields=knowledge_panels)

fix: KP panel groups sometimes have null title

---

lib/utils/ImageHelper.dart

Impacted file:
* `ImageHelper.dart`: added flexibility and `ImageSize` parametered methods; fixed a minor bug (trailing slash)
- Refactoring around `ImageHelper`
- https://github.com/openfoodfacts/smooth-app/issues/3065
- https://github.com/openfoodfacts/smooth-app/pull/3088

fix: ImageHelper - new methods with ImageSize parameters + minor fix

---

lib/model/LoginStatus.dart
lib/openfoodfacts.dart
test/user_management_test_test_env.dart

Before we just returned a LoginStatus when the login was succesful (else null), with that approach `success`, `status` and `status_verbose` would have always been the same. Now we return also in case of bad credentials

fix: Also return [LoginStatus] when not logged in

---

lib/model/KnowledgePanelElement.dart
lib/model/KnowledgePanelElement.g.dart
test/knowledge_panels_from_json_test.dart

* `knowledge_panels_from_json_test.dart`: `'type'` instead of `'text_type'`
* `KnowledgePanelElement.dart`: `'type'` instead of `'text_type'`
* `KnowledgePanelElement.g.dart`: generated
- A JSON field of `KnowledgePanelTextElement` was misspelt.
- Now we use `'type'` instead of `'text_type'`
- Fixes #592

fix: #592 - KnowledgePanelTextElement - 'type' instead of 'text_type'

---

lib/openfoodfacts.dart
lib/utils/TagType.dart
lib/utils/TaxonomyQueryConfiguration.dart
test/api_getProduct_test.dart
test/api_get_autocompleted_suggestions_test.dart

* `api_get_autocompleted_suggestions_test.dart`: added tests for ORIGINS autocomplete
* `api_getProduct_test.dart`: minor refactoring
* `openfoodfacts.dart`: minor refactoring
* `TagType.dart`: added ORIGINS; refactored "à la 2.17"
* `TaxonomyQueryConfiguration.dart`: minor refactoring
- Implemented autocomplete for ORIGINS
- #596

feat: #596 - implemented autocomplete for ORIGINS

---

lib/openfoodfacts.dart
test/api_getProduct_test.dart

* `api_getProduct_test.dart`: tested that conf is not passed as parameter
* `openfoodfacts.dart`: removed config parameters from product URI
- By default, when we compute a URI the configuration parameters are passed.
- Which is not a desired feature for product URI.
- Therefore we explicitly remove them for product URI.
- Fixes #507

fix: #507 - no more parameters in product URI

---

lib/model/Product.dart
lib/model/Product.g.dart
lib/utils/ProductFields.dart
test/api_getProduct_test.dart

* `api_getProduct_test.dart`: added a test on the new "website" product field
* `Product.dart`: added the "website" field
* `ProductFields.dart`: added the "website" field
- Just added the "website" product field (offTag: `'link'`)
- Closes #602
- https://github.com/openfoodfacts/smooth-app/issues/2738
- https://github.com/openfoodfacts/smooth-app/issues/3207

feat: #602 - added the "website" product field

---

lib/model/SignUpStatus.dart

- SignupStatusError Response gave long html response which was actually use of incorrect email address which was not added as a response .

fix: Added response for incorrect email

---

lib/model/TaxonomyAdditive.dart
lib/model/TaxonomyAllergen.dart
lib/model/TaxonomyCategory.dart
lib/model/TaxonomyCountry.dart
lib/model/TaxonomyIngredient.dart
lib/model/TaxonomyLabel.dart
lib/model/TaxonomyLanguage.dart
lib/model/parameter/TagFilter.dart
lib/utils/AbstractQueryConfiguration.dart
lib/utils/OpenFoodAPIConfiguration.dart
lib/utils/ProductListQueryConfiguration.dart
lib/utils/ProductQueryConfigurations.dart
lib/utils/ProductSearchQueryConfiguration.dart
lib/utils/TaxonomyQueryConfiguration.dart

* `AbstractQueryConfiguration.dart`: removed deprecated field `cc`
* `OpenFoodAPIConfiguration.dart`: removed deprecated field `globalCc`
* `ProductListQueryConfiguration.dart`: removed deprecated field `cc`
* `ProductQueryConfigurations.dart`: removed deprecated field `cc`
* `ProductSearchQueryConfiguration.dart`: removed deprecated field `cc`
* `TagFilter.dart`: refactored with `OffTagged`; removed deprecated constructor
* `TaxonomyAdditive.dart`: removed deprecated field `cc`
* `TaxonomyAllergen.dart`: removed deprecated field `cc`
* `TaxonomyCategory.dart`: removed deprecated field `cc`
* `TaxonomyCountry.dart`: removed deprecated field `cc`; refactored with `OffTagged`
* `TaxonomyIngredient.dart`: removed deprecated field `cc`
* `TaxonomyLabel.dart`: removed …

refactor: used OffTagged and removed deprecated fields

---

lib/model/TaxonomyPackagingRecycling.dart
lib/model/TaxonomyPackagingRecycling.g.dart
lib/openfoodfacts.dart
lib/utils/TagType.dart
test/api_getTaxonomyPackagingRecyclingServer_test.dart
test/api_get_autocompleted_suggestions_test.dart

New files:
* `api_getTaxonomyPackagingRecyclingServer_test.dart`: server tests around Packaging Recycling Taxonomy
* `TaxonomyPackagingRecycling.dart`: Packaging Recycling Taxonomy classes
* `TaxonomyPackagingRecycling.g.dart`: generated
* `api_get_autocompleted_suggestions_test.dart`: added suggestion tests for packaging recycling
* `openfoodfacts.dart`: added method `getTaxonomyPackagingRecycling`
* `TagType.dart`: added field type for packaging recycling
- Taxonomy: support of packaging recycling
- Closes: #614

feat: #614 - taxonomy - support of packaging recycling

---

test/api_getTaxonomyPackagingRecyclingServer_test.dart

- New data on the server means we need to refresh the integration tests.

fix: integrationTest with packaging recycling

---

lib/model/NutrientLevels.dart
lib/model/Product.dart
lib/model/ProductImage.dart
lib/model/SendImage.dart
lib/model/State.dart
lib/openfoodfacts.dart
lib/utils/AbstractQueryConfiguration.dart
lib/utils/CountryHelper.dart
lib/utils/ImageHelper.dart
lib/utils/JsonHelper.dart
lib/utils/LanguageHelper.dart
lib/utils/OpenFoodAPIConfiguration.dart
lib/utils/ProductFields.dart
lib/utils/TaxonomyQueryConfiguration.dart
lib/utils/UriHelper.dart
test/api_getProduct_test.dart
test/ordered_nutrient_test.dart

* `AbstractQueryConfiguration.dart`: minor refactoring
* `api_getProduct_test.dart`: minor refactoring
* `CountryHelper.dart`: upgraded `OpenFoodFactsCountry` to dart 2.17
* `ImageHelper.dart`: minor refactoring
* `JsonHelper.dart`: minor refactoring
* `LanguageHelper.dart`: upgraded `OpenFoodFactsLanguage` to dart 2.17
* `NutrientsLevels.dart`: upgraded `Level` to dart 2.17
* `OpenFoodAPIConfiguration.dart`: minor refactoring
* `openfoodfacts.dart`: minor refactoring
* `ordered_nutrient_test.dart`: minor refactoring
* `Product.dart`: minor refactoring
* `ProductFields.dart`: minor refactoring
* `ProductImage.dart`: upgraded `ImageField`, `ImageSize`, `ImageAngle` to dart 2.17; minor refactoring
* `SendImage.dart`: minor refactoring
* `State.dart`: upgraded `State` to dart …

fix: #571 - last step of migration of enums to dart 2.17

---

lib/utils/HttpHelper.dart

Impacted file:
* `HttpHelper.dart`
- The user credentials are added in the request header only for Robotoff, for `api/v1/insights/annotate` and `api/v1/predict/ingredients/spellcheck`
- In the special case when the user is `null`, we should NOT try to populate the request header with it - that's what this PR fixes
- Closes #625

fix: #625 - no user credentials in header if null

---

lib/openfoodfacts.dart
test/api_getRobotoff_test.dart

* `api_getRobotoff_test.dart`: removed test related to `getIngredientSpellingCorrection`
* `openfoodfacts.dart`: deprecated method `getIngredientSpellingCorrection` that does not work
Closes #223

fix: #223 - deprecated method getIngredientSpellingCorrection

---

test/api_getRobotoff_test.dart

Impacted file:
* `api_getRobotoff_test.dart`
- For historical reasons we were expecting many populated fields from Robotoff, and in some cases - especially with the "give me some random data" test - some fields are _not_ populated.
- Those "unsafe" fields are now removed from the tests.
- Fixes: #575

fix: 575 - less expected populated fields from Robotoff

---

test/api_searchProducts_test.dart

Impacted file:
* `api_searchProducts_test.dart`: added a specific test for nova group filter; switched tests to PROD env whenever possible
- Just added a test on nova group filter - the filtering was already there (but was not really tested).
- Closes: #539

feat: 539 - specific test for nova group filter

---

lib/model/Nutriments.dart
test/api_getProduct_test.dart

* `api_getProduct_test.dart`: added tests around new method `Nutriments.isEmpty`
* `Nutriments.dart`: new method `isEmpty`; added comments
- cf. #648
- Closes: #648

feat: 648 - new method "Nutriments.isEmpty"

---

LICENSE

Impacted file:
* `LICENSE`: found format inspiration in https://pub.dev/packages/image_editor/score
- In order to get 10 pts closer to the max pub.dev score
- Fixes: #548

fix: 548 - "LICENSE" refactoring

---

test/api_search_products_test.dart

Impacted file:
* `api_search_products_test.dart`: slightly edited a test in order to be less intense for the server
- Filter on NOVA looks very demanding on the server resources, and for NOVA 4 it may lead to Mongo DB crash.
- The fix here is about switching to a country with less data than France - in this case, Poland.
- Fixes: #650

fix: 650 - less server demanding nova integration test

---

lib/src/model/product_packaging.dart
lib/src/model/product_packaging.g.dart
test/api_save_product_v3_test.dart

* `api_save_product_v3_test.dart`: added test for new packaging fields `quantityPerUnit` and `weightMeasured`
* `product_packaging.dart`: added fields `quantityPerUnit` and `weightMeasured`
* `product_packaging.g.dart`: generated
- New packaging fields `quantityPerUnit` and `weightMeasured`
- Closes: #662

feat: 662 - new packaging fields "quantityPerUnit" and weightMeasured"

---

lib/src/model/product.dart
lib/src/model/product.g.dart
lib/src/open_food_api_client.dart
lib/src/utils/json_helper.dart
lib/src/utils/product_fields.dart
test/api_save_product_v3_test.dart

* `api_save_product_v3_test.dart`: added a save/read test about new product field `packagingsComplete`
* `json_helper.dart`: added helper methods about bool to/from 0/1 conversion.
* `open_food_api_client.dart`: added a way to save new product field `packagingsComplete`
* `product.dart`: added field `packagingsComplete`
* `product_fields.dart`: added field `PACKAGINGS_COMPLETE`
- Support of new product field "packagingsComplete" through api V3.
- It's a `bool?`, coded as int 0 and 1.
- Closes: #659

feat: 659 - support of product field "packagingsComplete"

---

lib/src/model/parameter/tag_filter.dart
lib/src/utils/user_product_search_query_configuration.dart
test/api_get_user_products_test.dart

* `api_get_user_products_test.dart`: now supporting api v3
* `tag_filter.dart`: added filters `PHOTOGRAPHERS` and `INFORMERS`
* `user_product_search_query_configuration.dart`: deprecated
- User related product queries used a specific syntax, that made them incompatible with api v3.
- Now we use the standard syntax with new parameters.
- Therefore user related product queries now support api v3.
- Closes: #617

fix: 617 - user related queries now support api v3

---

lib/src/open_food_api_client.dart
lib/src/utils/product_query_configurations.dart
lib/src/utils/product_search_query_configuration.dart
test/api_get_to_be_completed_products_test.dart
test/api_matched_product_v2_test.dart
test/api_search_products_test.dart

* `api_get_to_be_completed_products_test.dart`: minor refactoring
* `api_matched_product_v2_test.dart`: minor refactoring
* `api_search_products_test.dart`: added version
* `open_food_api_client.dart`: api version is now required for `getProductFreshness`
* `product_query_configurations.dart`: api version is now required for `ProductQueryConfiguration`; deprecated version 0, (1) and 2
* `product_search_query_configuration.dart`: api version is now required for `ProductSearchQueryConfiguration`
- It became embarrassing not to ask explictly for the api version and setting default versions instead: should we have different api versions for different methods? Should we upgrade the versions without notifying the user?
- A solution, implemented here, was to make the version a …

refactor!: 658 - api version is now required for barcode and search queries

---

analysis_options.yaml
lib/src/model/product.g.dart
lib/src/model/product_result.g.dart
lib/src/model/robotoff_question.dart
lib/src/model/status.dart
lib/src/model/user.dart
lib/src/model/user_agent.dart
lib/src/utils/barcodes_validator.dart

* `analysis_options.yaml`: as close as the recommendations as possible
* `barcodes_validator.dart`: minor refactoring
* `product.g.dart`: ugly minor refactoring
* `product_result.g.dart`: ugly minor refactoring
* `robotoff_question.dart`: minor refactoring
* `status.dart`: minor refactoring
* `user.dart`: minor refactoring
* `user_agent.dart`: minor refactoring
- Unexpectedly with 2.0.0 we still haven't reached the max score of 140 on pub.dev.
- Part of the reason is that pub.dev does check the generated files, and we did not.
- Now our check parameters are as close to pub.dev as possible.
- Hopefully when this PR is merged into pub.dev we get the max score!

refactor: lint - as close to pub.dev as possible in order to pass the checks

---

lib/src/utils/product_search_query_configuration.dart

Impacted file:
* `product_search_query_configuration.dart`: fixed lint error
- Fix of a lint error found on pub.dev but that we didn't detect locally.

fix: fixed lint error

---

test/api_get_robotoff_test.dart
test/api_matched_product_v1_test.dart
test/api_search_products_test.dart
test/ordered_nutrient_test.dart

* `api_get_robotoff_test.dart`: switched to PROD env
* `api_matched_product_v1_test.dart`: switched to PROD env
* `ordered_nutrient_test.dart`: switched to PROD env
- [pub.dev](https://pub.dev/packages/openfoodfacts) says that [our tests are failing](https://github.com/openfoodfacts/openfoodfacts-dart/actions/workflows/test-sdk.yml).
- More precisely, it's a read-only test on TEST env.
- As TEST env is notoriously less stable than PROD, the goal of this PR is to switch to PROD env some read-only tests.

fix: more read-only tests on PROD env

---

lib/src/utils/http_helper.dart

Impacted file:
* `http_helper.dart`
- We experience problems in Smoothie regarding the value of user agent for some queries.
- We recently switched those queries from POST to GET.
- And anyway the spelling of `User-Agent` was wrong.
- cf. https://github.com/openfoodfacts/smooth-app/pull/3546#issuecomment-1376043349
- https://github.com/openfoodfacts/smooth-app/issues/3534

fix: correct spelling of User-Agent

---

lib/src/open_food_api_client.dart
lib/src/utils/image_helper.dart
test/api_get_product_image_ids_test.dart
test/api_get_product_test.dart
test/api_matched_product_v1_test.dart
test/api_matched_product_v2_test.dart
test/api_search_products_test.dart

New file:
* `api_get_product_image_ids_test.dart`: tests around `OpenFoodAPIClient.getProductImageIds`.
* `image_helper.dart`: new method `getUploadedImageUrl`
* `open_food_api_client.dart`: new method `getProductImageIds`
- New method `getProductImageIds`, that returns all uploaded image ids for a `Product`.
- #688

feat: 688 - new method "getProductImageIds"

---

lib/src/model/product.dart
lib/src/model/product_image.dart
lib/src/utils/json_helper.dart
test/api_json_to_from_test.dart
test/api_search_products_test.dart

New file:
* `api_json_to_from_test.dart`: unit tests about to/from json conversions
* `api_search_products_test.dart`: unrelated fix
* `json_helper.dart`: implemented method `imagesToJson`; refactored method `imagesFromJson`
* `product_images.dart`: added fields width and height; added `hashcode` and `==` operator
- `imagesFromJson`was already implemented, but not `imagesToJson`.
- That was problematic if we wanted to store locally in a `String` a `Product` with field `images`.
- Closes: #691
- Closes: #692

fix: 691 - implemented "imagesToJson"

---

README.md
example/lib/main.dart
lib/src/open_food_api_client.dart
pubspec.yaml
test/api_get_product_test.dart
test/api_get_suggestions_test.dart
test/api_save_product_test.dart

New file:
* `api_get_suggestions_test.dart`: Integration tests about the V3 suggestions.
* `api_get_autocompleted_suggestions_test.dart`: added an `ignore` against deprecation warnings.
* `api_get_product_test.dart`: unrelated fix.
* `main.dart`: now using new method `getSuggestions`.
* `open_food_api_client.dart`: new method `getSuggestions`; deprecated method `getAutocompletedSuggestions`
* `pubspec.yaml`: unrelated package upgrades.
- New API V3 suggestions for taxonomies
- Closes: #695

feat: 695 - New API V3 suggestions for taxonomies

---

lib/src/personalized_search/matched_product_v2.dart
pubspec.yaml
test/api_matched_product_v2_test.dart

* `api_matched_product_v2_test.dart`: refactored around the test for new class `MatchedScoreV2`
* `matched_product_v2.dart`: new class `MatchedScoreV2`
* `pubspec.yaml`: unrelated upgrade
- When we have tons of `Product`s to sort according to scores, it is useful to compute the score without storing the product (which can be fat), for memory performance reason.
- The new class `MatchedScoreV2` computes the score but stores just the barcode, not the whole `Product`.
- The previous class `MatchedProductV2` still exists but just extends `MatchedScoreV2`.
- Closes: #699

feat: 699 - new class MatchedScoreV2 with better perf than MatchedProductV2

---

pubspec.yaml

Impacted file:
* `pubspec.yaml`
- If we don't rollback here too, we cannot use off-dart in Smoothie...

fix: rollback to dart 2.17 / flutter 3.0.5

---

lib/src/open_food_api_client.dart

Impacted file:
* `open_food_api_client.dart`
- The `User` parameter is optional for get random robotoff questions
- #712
- https://github.com/openfoodfacts/smooth-app/issues/3600

fix: 712 - optional User parameter for get random robotoff questions

---

test/api_get_robotoff_test.dart
test/api_post_robotoff_test.dart

* `api_get_robotoff_test.dart`
* `api_post_robotoff_test.dart`
- In #723 methods were deprecated, and that's not good for our tests!
- #723

fix: robotoff deprecated method calls in tests

---

pubspec.yaml

Impacted file:
* `pubspec.yaml`: downgraded `path` to ^1.8.2 in order to match `flutter_test`'s `path`
- We used `path: ^1.8.3`, but `flutter_test` uses `1.8.2`, which caused dependency issues for flutter projects.
- As `1.8.2` is good enough for us, in the current PR we downgrade the `path` version to `^1.8.2`
- Closes: #715

fix: 715 - downgraded "path" in order to match "flutter_test"

---

lib/src/model/nutrient.dart

- There was a typo for mono and poly unsaturated fat tags: a trailing `-tag` was missing in both cases.
- This is fixed in this PR.
- https://github.com/openfoodfacts/smooth-app/issues/3980

fix: typo for mono and poly unsaturated fat tags

---

lib/openfoodfacts.dart
lib/src/model/knowledge_panel_action.dart
lib/src/model/knowledge_panel_element.dart

New file:
* `knowledge_panel_action.dart`: Possible needed contribute actions.
* `knowledge_panel_element.dart`: deprecated const String in favor of the new enum
* `openfoodfacts.dart`: exported the new file
- Simple refactoring, using `OffTagged`
- Fixes: #729

refactor: new "KP action" enum

---

test/api_get_user_products_test.dart

- While reviewing #748, I noticed an unrelated bug in the tests.
- The fix is only to set a higher number of downloaded items, so that the algorithm of the test does work.
* `api_get_user_products_test.dart`: fixed a test bug (set a higher limit)

fix: get user products tests

---

lib/src/robot_off_api_client.dart
test/api_get_robotoff_test.dart

Hi everyone 🖐️!
We can now filter questions by giving one or more insight types.
This is not yet deployed (waiting for https://github.com/openfoodfacts/robotoff/pull/1134), so please don't merge this PR yet.
But we'll be ready once it's OK.

feat: Allow to pass `insight_types` to `api/v1/questions/$barcode`

---

lib/src/open_food_api_client.dart
test/user_management_test_prod.dart

Hi everyone,
Today, all users are registered on the `world.openfoodfacts.org` subdomain.
If they choose to also subscribe to the newsletter, they will receive it in English, but we have translated issues.
That's why we can now pass a country and/or a language.
It will fix #753

feat: Allow to pass a country and/or a language to the `register` user method

---

.github/workflows/release-please.yml

The release was not triggered due to GitHub's recursive run protection. Now we releases using the Openfoodfacts-bot account

ci: release

---

test/api_add_product_image_test.dart
test/api_get_product_test.dart
test/api_get_robotoff_test.dart
test/api_get_save_product_test.dart
test/api_get_to_be_completed_products_test.dart
test/api_ocr_ingredients_test.dart
test/api_search_products_test.dart

- Fixed some unit tests.
New file:
* `api_get_save_product_test.dart`: moved there read-write tests from `api_get_product_test.dart`
* `api_add_product_image_test.dart`: skipped tests on unreliable TEST env
* `api_get_product_test.dart`: now we're focused on read-only tests in PROD; we moved the read-write tests to new file `api_get_save_product_test.dart`
* `api_get_robotoff_test.dart`: fixed special cases with specific insight types
* `api_get_to_be_completed_products_test.dart`: added a filter on stores for less demanding queries
* `api_ocr_ingredients_test.dart`: fixed async tests with no await
* `api_search_products_test.dart`: added a filter in order to make the query less server intensive - and less prone to server crash

fix: fixed unit tests

---

README.md

A tiny change to have a link to Pub.dev on the first badge

chore: Add a link to Pub.dev on the badge

---

lib/src/open_food_api_client.dart

Hi everyone,
As part of https://github.com/openfoodfacts/smooth-app/issues/3740, I've noticed that the Dart package checks the length of the username.
But actually, the check is done on the name and not the username.

fix: The registration checks the username length on the wrong field

---

lib/src/model/sign_up_status.dart
lib/src/open_food_api_client.dart

Hi everyone,
Due to the current situation with the infrastructure, we often have 504 errors.
Here is a better catch of the errors for the registration and the password lost.
It's here limited to the user management, but it's more critical here.

feat: Registration/Password lost: better catch 504 errors from the server

---

lib/src/utils/http_helper.dart

Hi everyone,
We have a major issue with POST requests, where we only get a part of the response (`first` from a `Stream`).
This PR ensures to get the full response

feat: Multipart requests: ensure to always get the full response

---

lib/src/open_food_api_client.dart
test/user_management_test_prod.dart

Hi everyone,
When we want to reset the password of the user, we use the world instance of OFF.
By providing a country and/or language, the user will then receive the localized content

feat: Reset password: allow to receive "translated" email

---

lib/src/open_food_api_client.dart
test/user_management_test_prod.dart

- Not that long ago there was no country or language parameters on reset password. We lousily tried to detect sentences in the resulting html.
- Now that we have country or language parameters, we get a localized html. The sentences we expected are localized. That's why in this PR we use html tags instead of localized terms.
- That's still very lousy: we would be better off calling a more appropriate server URL that would return a json. But that does not exist AFAIK.
- https://github.com/openfoodfacts/smooth-app/issues/4549
* `open_food_api_client.dart`: relying on html tags for error detection instead of English localizations
* `user_management_test_prod.dart`: additional tests with / without language/country and on existing / not existing users

fix: reset password checks with languages

---

lib/src/utils/image_helper.dart

- Uploaded images have a minimum accepted size. Smaller images get rejected.
- In order to avoid this, developers can check the image size before trying to upload them.
- This is what we do in Smoothie. With this PR we can do that from values taken from off-dart.
* `image_helper.dart`: specified minimum size for uploaded images

feat: specified minimum size for uploaded images (for pre-checks)

---

lib/src/utils/uri_helper.dart

- This is a method we had to implement in Smoothie.
- Typical use-case: trying to ping the server after a connection failed.
- Now we can get the uri host directly.
* `uri_helper.dart`: new `getUriHost` method

feat: method to get the Uri host (e.g. for ping)

---

lib/src/model/insight.dart

- In Smoothie we had to implement that method.
- Now we implement that method directly in off-dart.
* `insight.dart`: implemented the `fromInt` method for `InsightAnnotation`

feat: insight - method to get an insight annotation from an int value

---

lib/src/utils/server_type.dart

- We forgot to implement a method to get a server type from an off tag (e.g. `off`, `obf`, `opf` and `opff`).
- We need this method for Smoothie in order to store the server type into preferences.
- #69
* `server_type.dart`: implemented the `fromOffTag` method

feat: 69 - method to get a server type from its off tag

---

lib/src/open_food_api_client.dart
lib/src/utils/country_helper.dart
test/api_off_tag_test.dart
test/ordered_nutrient_test.dart

- In Smoothie we detected a possible bug regarding our usage of 'uk' as United Kingdom country code - while the official country code is 'gb'.
- It got fixed in Smoothie - the current PR is about fixing it in off-dart too.
- Meanwhile, country related minor issues were fixed. Those are minor breaking changes, that will be embedded in the already "breaking change" next release.
* `country_helper.dart`: `fromOffTag` now includes a fix for the uk/gb case; breaking change - removed class `CountryHelper`
* `open_food_api_client.dart`: breaking change - `getOrderedNutrients` now uses parameter `OpenFoodFactsCountry country`
* `ordered_nutrient_test.dart`: minor refactoring

fix!: fix for the uk/gb country code case

---

lib/src/model/product.dart
lib/src/model/product.g.dart
lib/src/utils/product_fields.dart
test/api_get_localized_product_test.dart
test/api_get_product_test.dart

- Added 6 localized products fields
- `brandsTagsInLanguages`
- `ingredientsAnalysisTagsInLanguages`
- `miscTagsInLanguages`
- `statesTagsInLanguages`
- `tracesTagsInLanguages`
- `storesTagsInLanguages`
- Fixed product field `miscTags` (that was always `null`)
- Refactored the code instead of copying/pasting again and again.
- Closes: #810
New file:
* `api_get_localized_product_test.dart`: unit tests about getting localized product fields
* `api_get_product_test.dart`: just moved 2 tests to new file `api_get_localized_product_test.dart`
* `product.dart`: fixed field `miscTags`; added fields `brandsTagsInLanguages`, `ingredientsAnalysisTagsInLanguages`, `miscTagsInLanguages`, `statesTagsInLanguages`, `tracesTagsInLanguages`, `storesTagsInLanguages`; refactored …

feat: 810 - 6 new localized product fields

---

lib/src/model/product.dart
test/api_get_save_product_test.dart

- From about a week ago, `productName` and `ingredientsText` could not be 100% trusted anymore in a multilingual context.
- More specifically, you could not trust the product name to be in German if you asked for a list of languages with German first (on a product that has German and other translations).
- The solution is to use the localized version of `productName`. And as a fallback, `productName`.
- Same thing for `ingredientsText`.
- The unit tests failed and that's the reason of the current PR.
- Fixes: #816
* `api_get_save_product_test.dart`: removed tests on productName and ingredientsText; refactored
* `product.dart`: added comments about using rather the localized fields for productName and ingredientsText

fix: 816 - use localized versions of productName and ingredientsText

---

lib/src/model/search_result.dart
lib/src/model/search_result.g.dart
test/api_get_user_products_test.dart
test/api_search_products_test.dart

- New field `pageCount` for `SearchResult`
- That will help us solve a minor rare discrepancy between the number of "returned products", the "number of returned products" (`pageCount`) and the "total number of products" (`count`).
* `api_get_user_products_test.dart`: now using `pageCount` instead of `count`
* `api_search_products_test.dart`: skipped a test failing because of the server
* `search_result.dart`: added field `pageCount`
* `search_result.g.dart`: generated

feat: new field pageCount for searchResult

---

lib/src/model/parameter/pnns_group2_filter.dart
lib/src/utils/pnns_groups.dart

- Some refactoring around pnns groups, that were using a slightly obscure syntax that we can avoid now due to dart syntax evolution.
* `pnns_group2_filter.dart`: minor refactoring
* `pnns_groups.dart`: used a clearer syntax

chore: pnnsGroup refactoring

---

lib/src/model/product.dart
lib/src/model/product.g.dart
lib/src/utils/product_fields.dart
test/api_get_save_product_test.dart

- One test started to fail yesterday.
- Obviously something changed on the server side regarding `genericName`, the same way it changed weeks ago about `productName`. In short, now you're supposed to be explicit regarding the language you use, which is a good news. I fixed the test.
- En passant, I also added a localized version of "generic name".
* `api_get_save_product_test.dart`: set explicit language for `genericName` test to pass; also tested new field `genericNameInLanguages`
* `product.dart`: added field `genericNameInLanguages`
* `product_fields.dart`: added fields `GENERIC_NAME_IN_LANGUAGES` and `GENERIC_NAME_ALL_LANGUAGES`

feat: new localized product fields for generic name

---

lib/src/utils/http_helper.dart
test/user_management_test_test_env.dart

- We populate the `From` http header with the user name
- Which may be problematic, as data in the http header is supposed to be ASCII/ISO-8859-1 encoded.
- In order to prevent the http header from being rejected, we transform user name if from another charset.
- cf. https://github.com/openfoodfacts/smooth-app/issues/4813
- #829
* `http_helper.dart`: safer `From` http header.
* `user_management_test_test_env.dart`: new test if the login crashes with a non-ASCII/ISO-8859-1 username

fix: 829 - no more crash if the user name is not ASCII/ISO-8859-1

---

lib/src/model/sign_up_status.dart
lib/src/model/status.dart
lib/src/open_food_api_client.dart

- Some refactoring about "server error", where we put status=500 and an error message in English.
- Just use new method `shouldOpenNewIssue` in order to:
- localize a standard "server error" message
- use `openNewIssueUrl` as a "open new issue" url...
- Closes: #836
- https://github.com/openfoodfacts/smooth-app/issues/4836
* `open_food_api_client.dart`: minor refactoring
* `status.dart`: new method `shouldOpenNewIssue` and constant fields `openNewIssueUrl` and `serverErrorStatus`
* `sign_up_status.dart`: minor refactoring

feat: 836 - localizable and clickable server error

---

test/api_ocr_ingredients_test.dart

- Tesseract tests recently failed because of the server, cf. https://github.com/openfoodfacts/openfoodfacts-server/issues/9401
- Meanwhile we skip those tests here in off-dart.

chore: skip tesseract tests with server errors

---

lib/src/open_food_search_api_client.dart
lib/src/search/fuzziness_level.dart
lib/src/search/taxonomy_name.dart
test/api_search_test.dart

- Added all taxonomy names and all fuzziness levels for the Elastic Search autocomplete.
- Closes: #620
* `api_search_test.dart`: added tests for all taxonomy names and all fuzziness levels
* `fuzziness_level.dart`: added all fuzziness values
* `open_food_search_api_client.dart`: added a comment
* `taxonomy_name.dart`: added all taxonomy names

feat: 620 - autocomplete for all taxonomy names and fuzziness levels

---

lib/src/open_food_api_client.dart
test/api_get_product_image_ids_test.dart

Hi everyone!
As noticed in the OFF app, when in the json, `product -> images` is `null`, the code crashes because we assign it to a non-null Map.

fix: If `product -> images` is `null`, `getProductImageIds`shouldn't crash

---

test/api_get_save_product_test.dart

- The purpose of this PR is to get rid of annoying emails about some specific tests non passing.
- In that particular case, the TEST server is often funny in its head, and `getProductV3` (and of course the corresponding URL) systematically fails with a `502 Bad Gateway` error.
- Instead of receiving error messages about problems that do not regard our code but the current status of the TEST env, we check first if a simple `getProductV3` call works. If it triggers a `502`, we ignore the test. If it passes, we run the test. IF there's another exception, we fail the test.

chore: test TEST server first before some tests around getProductV3

---

lib/src/model/nutrient.dart

Added 18 nutrients:
- Omega 9
- ß-Carotene
- Bicarbonate
- Sugar Alcohol (polyol)
- and 14 acids
- #862

fix: 862 - added 18 nutrients

---

lib/src/utils/http_helper.dart
test/api_get_product_test.dart

- Fixed a unit test value
- Improved the json decoding when the server is down. Something like
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ð Service Downtime Notification - Open Food Facts ð</title>
<style>
```
* `api_get_product_test.dart`: updated expected value
* `http_helper.dart`: handled the `<!DOCTYPE html>` returned from the server when jsondecoding

fix: unit test value + better json decode

---

lib/src/model/nutrient.dart

- Added enumeration support for "added-sugars"
- Nutrient already supported server-side https://github.com/openfoodfacts/openfoodfacts-server/blob/acf96bb5625f02ea1bc3bc0bcbdb82153a896517/taxonomies/nutrients.txt#L2098
- #862

fix: 862 - added 1 nutrient

---

lib/src/model/product.dart
lib/src/model/product.g.dart
lib/src/utils/product_fields.dart
test/api_get_product_test.dart

- New bool "obsolete" product field.
- #878
- https://github.com/openfoodfacts/smooth-app/issues/5005
* `api_get_product_test.dart`: tested the new product "obsolete" field on an obsolete and a non-obsolete product
* `product.dart`: added the "obsolete" field
* `product.g.dart`: wtf
* `product_fields.dart`: added the "OBSOLETE" product field

feat: 878 - added the "obsolete" product field

---

lib/src/folksonomy.dart

- Recent change in folksonomy, server-side (couple of days ago): unknown product tag search will return 404.
- This PR deals with it.
````log
❌ test/api_folksonomy_test.dart: OpenFoodAPIClient Folksonomy getProductTag - not found (failed)
Exception: Wrong status code: 404
package:openfoodfacts/src/folksonomy.dart 373:7  FolksonomyAPIClient._checkResponse
package:openfoodfacts/src/folksonomy.dart 172:5  FolksonomyAPIClient.getProductTag
===== asynchronous gap ===========================
test/api_folksonomy_test.dart 134:36             main.<fn>.<fn>
```

fix: folksonomy getProductTag may return 404

---

lib/openfoodfacts.dart
lib/src/open_prices_api_client.dart
lib/src/prices/get_parameters_helper.dart
lib/src/prices/get_prices_order.dart
lib/src/prices/get_prices_parameters.dart
test/api_prices_test.dart

- More refined parameters for the "get prices" API query.
- Including the "order by" clause, useful for Smoothie (get the latest prices for that product).
- #831
New files:
* `get_parameters_helper.dart`: Helper class for API query parameters.
* `get_prices_order.dart`: Order clause for "get prices".
* `get_prices_parameters.dart`: Parameters for the "get prices" API query.
* `api_prices_test.dart`: elaborated the test of "get prices"
* `open_prices_api_client.dart`: refactored
* `openfoodfacts.dart`: 2 new exported files

feat: 831 - more parameters for the "get prices" API query

---

test/api_get_save_product_test.dart

- Fixed expected results as `'en:beverages'` is now a child of `'en:beverages-and-beverages-preparations'`

fix: unit tests around category "beverages"

---

lib/src/model/product_image.dart
lib/src/utils/json_helper.dart
test/api_json_to_from_test.dart

- Now we use the "uploaded timestamp" field that the server provided for raw images, but that we just didn't retrieve.
- With this field we'll be able to say if an uploaded image is "too old", e.g. if it was uploaded more than a year ago.
- #891
- https://github.com/openfoodfacts/openfoodfacts-server/issues/9226
- https://github.com/openfoodfacts/smooth-app/issues/4674
* `api_json_to_from_test.dart`: added tests around new field `uploaded`
* `json_helper.dart`: added the `uploaded` field to from/to json conversion methods; refactored
* `product_image.dart`: added field `uploaded`, for uploaded images only

feat: 891 - new "uploaded timestamp" field for raw images

---

lib/src/model/knowledge_panel_element.dart
lib/src/model/knowledge_panel_element.g.dart
lib/src/model/user.g.dart

- Added field `link_url` to `KnowledgePanelImageElement`
- _En passant_, fixed a tag and generated needed code for an unrelated topic.
- Fixes: #919
- https://github.com/openfoodfacts/smooth-app/issues/5191
* `knowledge_panel_element.dart`: added the `'link_url'` field; fixed the tag for `'alt'` field
* `knowledge_panel_element.g.dart`: generated
* `user.g.dart`: generated - I guess the latest changes in `user.dart` were not followed by `dart run build_runner build`

feat: 919 - new field KnowledgePanelImageElement.link_url

---

lib/src/prices/currency.dart
lib/src/utils/country_helper.dart
test/api_off_tag_test.dart

- Now each country has a default currency. Except Antarctica.
- Fixes: #922
- https://github.com/openfoodfacts/smooth-app/issues/5201
* `api_off_tag_test.dart`: added a test about the relationship between country and currency
* `country_helper.dart`: added a `Currency` field to `OpenFoodFactsCountry`
* `currency.dart`: added fields in order to detect the most important currencies; added comments.

feat: 922 - default currency for each country

---

lib/src/prices/location.dart
lib/src/prices/location.g.dart
test/api_get_product_test.dart
test/api_get_robotoff_test.dart
test/api_matched_product_v1_test.dart

- Added osm location fields `countryCode`, `osmKey` and `osmValue`
- Typical use cases for Smoothie:
- displaying the flag of the country for prices
- displaying an icon related to a location type (like, if it's a shop)
- Closes: #933
* `api_get_product_test.dart`: unrelated minor test fix
* `api_get_robotoff_test.dart`: unrelated minor test fix
* `api_matched_product_v1_test.dart`: unrelated minor test fix
* `location.dart`: added fields `countryCode`, `osmKey` and `osmValue`
* `location.g.dart`: generated

feat: 933 - added osm location fields (countryCode, osmKey, osmValue)

---

lib/src/utils/product_query_configurations.dart

- In order to get rid of `v0` queries, we now have a forced minimum of `v2` as a query version.
- Closes: #927

fix: 927 - minimum forced query version is now 2

---

lib/src/model/parameter/page_size.dart
lib/src/open_prices_api_client.dart
lib/src/prices/currency.dart
lib/src/prices/price.dart
lib/src/prices/proof.dart
lib/src/prices/proof_type.dart
test/api_get_taxonomy_origins_server_test.dart
test/api_get_user_products_test.dart
test/api_prices_test.dart
test/api_search_products_test.dart
test/api_suggestion_manager_test.dart

- Now we pass an `app_name` parameter to prices methods `uploadProof` and `createPrice`, for tracking purposes.
- Meanwhile, some refactoring, including trying to make all tests pass.
- And some new prices methods somehow needed by Smoothie.
* `api_get_taxonomy_origins_server_test.dart`: minor refactoring
* `api_get_user_products_test.dart`: set max page size to new server max page size (100)
* `api_search_products_test.dart`: set default page size to new server default page size (50)
* `api_suggestion_manager_test.dart`: now targeting PROD; minor refactoring
* `currency.dart`: new `fromName` method
* `open_prices_api_client.dart`: added `app_name` parameter for `uploadProof` and `createPrice`; refactored around new method `getUri`
* `page_size.dart`: added comments
* `price.dart`: added …

fix: added "app_name" parameter for prices methods uploadProof and createPrice

---

lib/src/open_prices_api_client.dart
lib/src/utils/http_helper.dart
lib/src/utils/uri_reader.dart
lib/src/utils/uri_reader_js.dart
test/api_add_product_image_test.dart

- Our home-made user agent prevents our dart package to work when used in web mode.
- We use this specific user agent for stats.
- The solution implemented here removes the user agent http header when in web mode, so that the package can be used.
- Possible improvements would be to change the way we build our user agent string (but that would have an impact on our previous/next stats), or where we put that home-made string (e.g. different http header tag) (but that would have an impact on our stats consistency too)
- We'll see how many requests we get from web mode. Later we can select one of the suggested improvements, or something else.
- Fixes: #937
* `api_add_product_image_test.dart`: minor refactoring
* `http_helper.dart`: removed home-made user agent header when for web; minor …

fix: 937 - removed home-made user agent header when for web

---

lib/src/model/user.dart
test/api_get_save_product_test.dart
test/user_management_test_prod.dart

- New static method `User.getUserWikiPage`
- Closes: #951
* `user.dart`: new method `getUserWikiPage`
* `user_management_test_prod.dart`: test of new method `User.getUserWikiPage`

feat: 951 - new method User.getUserWikiPage

---

lib/src/model/product_image.dart
lib/src/utils/json_helper.dart

Hi everyone,
On the `images` field, the API returns the contributor's name.
Eg:
```json
"images": {
"1": {
"sizes": {
"100": {
"h": 71,
"w": 100
},
"400": {
"h": 284,
"w": 400
},
"full": {
"h": 1089,
"w": 1536
}
},
"uploaded_t": 1345799270,
"uploader": "openfoodfacts-contributors"
```

feat: Add the name of the image contributor

---

lib/openfoodfacts.dart
lib/src/model/owner_field.dart
lib/src/model/product.dart
lib/src/model/product.g.dart
lib/src/utils/product_fields.dart
test/api_get_product_test.dart

- Added product owner fields.
- Closes: #956
New file:
* `owner_field.dart`: Helper class to compute the Product.ownerFields tags.
* `api_get_product_test.dart`: added a test for owner fields
* `openfoodfacts.dart`: added new class `OwnerField`
* `product.dart`: added field `ownerFields` and method `getOwnerFieldTimestamp`
* `product_fields.dart`: refactored around localized product fields

feat: 956 - added product owner fields

---

lib/src/folksonomy.dart
lib/src/prices/price_per.dart
lib/src/utils/http_helper.dart
test/api_folksonomy_test.dart

- We had no way to edit (add/update/delete) Folksonomy data, because we needed authentication.
- The authentication method is now available, and so are the "edit" methods.
- https://github.com/openfoodfacts/smooth-app/issues/5218
* `api_folksonomy_test.dart`: tests on the new folksonomy methods
* `folksonomy.dart`: new methods `getAuthenticationToken`, `addProductTag`, `deleteProductTag`, `updateProductTag`; minor refactoring
* `http_helper.dart`: new method `doPutRequest`
* `price_per.dart`: unrelated minor refactoring

feat: edit methods for folksonomy

---

lib/src/open_prices_api_client.dart
lib/src/prices/price_user.dart
lib/src/prices/price_user.g.dart
lib/src/prices/session.dart
test/api_prices_test.dart

- Minor refactoring around minor changes in the new Prices API (Django).
- #970
* `api_prices_test.dart`: refactored around new Prices API
* `open_prices_api_client.dart`: different status code for "delete user session"; simplified `updatePrice` and `updateProof`
* `price_user.dart`: field `isModerator` is now optional
* `price_user.g.dart`: generated
* `session.dart`: additional status codes and error messages

fix: 970 - refactored around new Prices API

---

lib/openfoodfacts.dart
lib/src/model/product.dart
lib/src/model/product.g.dart
lib/src/model/product_type.dart

- New field for `Product`: `ProductType? productType`.
- Values for food, beauty, pet food and product.
- Later, the server will populate this field.
- For the moment, we can say "hey, I extract data from openbeautyfacts, therefore I can manually set the type to `beauty` for my local data".
- Then we're able to say things like "hey, this is a `beauty` product, don't show the nutriscore!"
- Closes: #972
New file:
* `product_type.dart`: Type used at the product level (e.g. "this is a pet food product").
* `openfoodfacts.dart`: exported new file `product_type.dart`
* `product.dart`: added a new `ProductType?` field
* `product.g.dart`: (generated)

feat: 972 - new "product_type" field for Product

---

.github/workflows/github-projects.yml

- fix: Update github-projects.yml for OPF

fix: Update github-projects.yml for OPF

---

lib/openfoodfacts.dart
lib/src/open_prices_api_client.dart
lib/src/prices/location.dart
lib/src/prices/location.g.dart
lib/src/prices/price_product.dart
lib/src/prices/price_product.g.dart
lib/src/prices/price_total_stats.dart
lib/src/prices/price_total_stats.g.dart
lib/src/prices/price_user.dart
lib/src/prices/price_user.g.dart
lib/src/prices/proof.dart
lib/src/prices/proof.g.dart
lib/src/prices/proof_type.dart
test/api_get_product_test.dart
test/api_prices_test.dart

- New "total stats" endpoint
- Thumbnails for proofs
- New count fields for location, product, user
- New `SHOP_IMPORT` proof type
- Closes: #978
New files:
* `price_total_stats.dart`: Total stats for Prices.
* `price_total_stats.g.dart`: generated
* `api_get_product_test.dart`: unrelated minor fix
* `api_prices_test.dart`: added test for the new `getStats` method; added test for thumbnails
* `location.dart`: added new count fields
* `location.g.dart`: generated
* `open_prices_api_client.dart`: new method `getStats`
* `openfoodfacts.dart`: exported new file `price_total_stats.dart`
* `price_product.dart`: added new count fields
* `price_product.g.dart`: generated
* `price_user.dart`: added new count fields
* `price_user.g.dart`: generated
* `proof.dart`: added thumbnail …

feat: 978 - new prices features (thumbnails, stats)

---

lib/openfoodfacts.dart
lib/src/open_prices_api_client.dart
lib/src/prices/location.dart
lib/src/prices/location.g.dart
lib/src/prices/location_type.dart
lib/src/prices/maybe_error.dart
lib/src/prices/price.dart
lib/src/prices/price.g.dart
lib/src/prices/price_total_stats.dart
lib/src/prices/price_total_stats.g.dart
lib/src/prices/proof.dart
lib/src/prices/proof.g.dart
lib/src/prices/update_price_parameters.dart
lib/src/prices/update_proof_parameters.dart
test/api_prices_test.dart

- Added latest Prices fields.
- Minor fix for `createPrice` - now we don't care if we cannot fully read the server response body, as long as the status code has the expected value. In order to prevent trying to recreate over and over a Price when the response body evolves.
- Closes: #986
- https://github.com/openfoodfacts/smooth-app/issues/5689
New file:
* `location_type.dart`: Type of the Location.
* `api_prices_test.dart`: refactored with the additional fields
* `location.dart`: added fields `locationType` and `websiteUrl`
* `location.g.dart`: generated
* `maybe_error.dart`: now we accept valid but unreadable responses
* `open_prices_api_client.dart`: safer `createPrice` method; refactored with the additional fields
* `openfoodfacts.dart`: added file `location_type.dart` …

feat: 986 - new Prices fields

---

lib/src/model/knowledge_panel.dart
lib/src/model/knowledge_panel.g.dart
test/api_get_product_test.dart

- New knowledge panel `bool? halfWidthOnMobile`  field
- Closes: #990
* `api_get_product_test.dart`: added a test for the new KP `halfWidthOnMobile` field
* `knowledge_panel.dart`: added `halfWidthOnMobile` field
* `knowledge_panel.g.dart`: wtf

feat: 990 - new knowledge panel "halfWidthOnMobile" field

---

lib/src/utils/product_fields.dart
test/api_not_food_get_product_test.dart

- Now the server provides the product field "product_type", so let's retrieve it.
- https://github.com/openfoodfacts/smooth-app/issues/5855
* `api_not_food_get_product_test.dart`: additional tests with new product field product_type
* `product_fields.dart`: added product_type as new product field

feat: product_type as new product field

---

lib/src/model/product.dart
lib/src/model/product.g.dart

* `product.dart`: made most fields as "includeIfNull: false", including product_type
* `product.g.dart`: impact only on product_type
- The product field "product_type" was ALWAYS included in the "toJson" conversion, _even if null_.
- That had some problematic side effects on the server, that _always_ saw a product_type provided for every "save product details" operation in Smoothie. And there's only one moment when this field should be sent: when we _create_ the product. Afterwards, any save operation will be rejected if we populate the product_type, even with the same value.
- Now the product field "product_type" is only populated in the "toJson" conversion when it's not null, which only happens in Smoothie when we create the product in the correct OxF server.
- Beyond that, in order to …

fix: product_type not included when null

---

lib/src/model/product.dart
lib/src/model/product.g.dart
lib/src/utils/product_fields.dart
test/api_get_product_test.dart

- Now we retrieve the "owner" field of product.
- Therefore, we can compare it to the uploader of raw images, and say if a main image is locked.
- Closes: #999
- https://github.com/openfoodfacts/smooth-app/issues/5394
* `api_get_product_test.dart`: new test "check if images are locked"
* `product.dart`: added field `owner` and methods around images - `isImageLocked`, `getLocalizedImage` and `getRawImage`
* `product_fields.dart`: added field `OWNER`

feat: 999 - added "bool? product.isImageLocked" method

---

lib/src/prices/location.dart
lib/src/prices/location.g.dart
test/api_prices_test.dart

- Now that we have ONLINE price locations, the OSM fields can be null.
- Without the current fix, the tests always fail.
* `api_prices_test.dart`: minor change
* `location.dart`: made OSM fields nullable
* `location.g.dart`: wtf

fix: for online price locations, no OSM fields

---

lib/src/model/product_image.dart
lib/src/utils/json_helper.dart

- Fixed an incorrect management of image contributor in the toJson/fromJson methods.
| before | after |
| -- | -- |
| ![Screenshot_1732804102](https://github.com/user-attachments/assets/548216d7-59ce-4ec2-a10b-40f0e88909c5) | ![Screenshot_1732805823](https://github.com/user-attachments/assets/445da23e-bd88-45f9-b8dd-8a67f6005717) |
- https://github.com/openfoodfacts/smooth-app/issues/5943
- #953
* `json_helper.dart`: contributor correctly included in `toJson`
* `product_image.dart`: contributor correctly included in `toString`

fix: contributor correctly displayed

---

lib/openfoodfacts.dart
lib/src/open_prices_api_client.dart
lib/src/prices/get_parameters_helper.dart
lib/src/prices/get_price_products_order.dart
lib/src/prices/get_price_products_parameters.dart
lib/src/prices/get_price_products_result.dart
lib/src/prices/get_price_products_result.g.dart
test/api_prices_test.dart

- New "get price products" method, needed for Smoothie's "top products" page
- #1011
- https://github.com/openfoodfacts/smooth-app/issues/5988
New files:
* `get_price_products_order.dart`: Field for the "order by" clause of "get price products".
* `get_price_products_parameters.dart`: Parameters for the "get price products" API query.
* `get_price_products_result.dart`: List of price product objects returned by the "get price products" method.
* `get_price_products_result.g.dart`: generated
* `api_prices_test.dart`: new tests around new `getPriceProducts` method; minor refactoring
* `get_parameters_helper.dart`: minor refactoring
* `open_prices_api_client.dart`: new `getPriceProducts` method
* `openfoodfacts.dart`: exported the new 3 files

feat: 1011 - new "getPriceProducts" method

---

LICENSE
lib/openfoodfacts.dart
lib/src/prices/price.dart
lib/src/prices/price.g.dart
lib/src/prices/price_type.dart
test/api_get_product_test.dart
test/api_prices_test.dart

- New "type of a price" field.
- Closes: #1003
New files:
* `price_type.dart`: Type of a Price.
* `api_prices_test.dart`: additional test on price type
* `openfoodfacts.dart`: exported the new file
* `price.dart`: added the price type field
* `price.g.dart`: generated

feat: 1003 - new price type field

---

pubspec.yaml

- As we're between 2 major flutter versions, we need to be more precise regarding the package version numbers we use in `pubspec.yaml`.
- #960
cc. @AffanShaikhsurab

chore: 960 - refreshed pubspec.yaml

---

pubspec.yaml

- Same as #1021, but with a little twist.
- Looks like recent versions of `json_serializable` use that brand new stupid syntax with `if(... case ...)`, which is not supported everywhere.
- Therefore, we have to use the best version of `json_serializable` without that syntax.
- Fixes: #1023
- #960

chore: 960 - refreshed pubspec.yaml, again

---

lib/openfoodfacts.dart
lib/src/open_prices_api_client.dart
lib/src/prices/discount_type.dart
lib/src/prices/price.dart
lib/src/prices/price.g.dart
lib/src/prices/update_price_parameters.dart
test/api_prices_test.dart

- OSM fields are now considered as nullable for Price as we can have online shops. Expecting non-nullable values caused crashes.
- _En passant_, added Price field `discountType`.
- Fixes: #1045
New file:
* `discount_type.dart`: Discount Type, for Prices.
* `api_prices_test.dart`: added specific test for issue 1045; new test for `getPrice`
* `open_prices_api_client.dart`: new `getPrice` method; added `discountType` to `createPrice` method
* `openfoodfacts.dart`: added new file `discount_type.dart`
* `price.dart`: fixed OSM related fields as nullable; added `discountType` field
* `price.g.dart`: generated
* `update_price_parameters.dart`: added `discountType` field and related business rules

fix: 1045 - OSM fields now nullable and discountType for Price

---

lib/src/utils/json_helper.dart
test/api_get_product_test.dart
test/api_get_save_product_test.dart
test/json_conversion_test.dart

- When we converted Products to/from json, we lost the distinction between `null` and empty packagings list (field `packagings`).
- As a consequence, we couldn't force the packagings to be empty, as it was considered as a null array, and therefore considered as "not changed".
- With this PR we can have `null` or empty packagings list, as they do mean something different.
- Unit tests were added in order to check the impact of that minor change.
- https://github.com/openfoodfacts/smooth-app/issues/6369
* `json_conversion_test.dart`: added related unit tests
* `json_helper.dart`: now we can have non-null but empty packagings

fix: ability to empty packagings list

---

example/lib/main.dart
lib/src/model/product.dart
lib/src/model/product.g.dart
lib/src/model/status.dart
lib/src/utils/product_fields.dart
test/api_add_product_image_test.dart
test/api_get_product_test.dart
test/api_get_save_product_test.dart
test/api_get_suggestions_test.dart
test/api_get_taxonomy_packaging_recycling_server_test.dart
test/api_save_product_test.dart
test/api_search_products_test.dart

- We had product fields about traces, but not the editable one.
- The PR adds the editable product field about traces.
- https://github.com/openfoodfacts/smooth-app/issues/4679
* `api_save_product_test.dart`: added tests about editable product field "traces"
* `product.dart`: added field "traces"
* `product_fields.dart`: added product field "traces"

feat: added editable product field "traces"

---

lib/src/model/ingredient.dart
lib/src/model/ingredient.g.dart
test/api_get_product_test.dart

Add `is_in_taxonomy` to the Ingredient object.
[This flag was added Apr 19, 2024 to the server](https://github.com/openfoodfacts/openfoodfacts-server/commit/bb240bcf5e6b23f0ee232327f69f9c7f28bdc0a6) but not yet integrated here.
https://github.com/openfoodfacts/openfoodfacts-dart/issues/1050

feat: added is_in_taxonomy field to ingredient

---

lib/src/utils/country_helper.dart

Add iso3Code field to OpenFoodFactsCountry enum to support 3-letter country codes (e.g., 'FRA' for France)
Closes: #1067
Ensure all countries are populated with valid ISO 3166-1 alpha-3 codes for use in Smoothie and other projects.

feat: Add iso3Code field to OpenFoodFactsCountry enum per #1067

---

lib/openfoodfacts.dart
lib/src/open_prices_api_client.dart
lib/src/prices/common_proof_parameters.dart
lib/src/prices/create_proof_parameters.dart
lib/src/prices/proof.dart
lib/src/prices/proof.g.dart
lib/src/prices/update_proof_parameters.dart
test/api_prices_test.dart

- Added 5 parameters for proof upload and update.
- Among them, `readyForPriceTagValidation` that is needed for bulk proof upload in Smoothie.
- Added 4 fields for proofs.
- Now sharing a common structure for proof upload and update parameters, offering more flexibility and code consistency.
- Closes: #1066
- https://github.com/openfoodfacts/smooth-app/issues/6560
New files:
* `common_proof_parameters.dart`: Common parameters for the "upload and update proof" API queries, including 5 new fields.
* `create_proof_parameters.dart`: Parameters for the "upload proof" API query.
* `api_prices_test.dart`: added more tests around proof upload and update; refactored accordingly
* `open_prices_api_client.dart`: changed the parameters of `uploadProof` for more flexibility
* …

feat: 1066 - new parameters for proof upload

---

lib/src/folksonomy.dart

- Now a "not found" response for "folksonomy get product tag" may be "[]" (and not only "null").
- Fixes: #1099

fix: 1099 - additional test for "folksonomy get product tag": "not found"

---

lib/openfoodfacts.dart
lib/src/folksonomy.dart
lib/src/model/value_count.dart
lib/src/model/value_count.g.dart
pubspec.yaml
test/api_folksonomy_test.dart

- Folksonomy: now we can get all the values linked to a key.
- We were already able to get all the keys.
- Closes: #1104
- https://github.com/openfoodfacts/smooth-app/issues/6019
New files:
* `value_count.dart`: Folksonomy - statistics around a value.
* `value_count.g.dart`: generated
* `api_folksonomy_test.dart`: added tests about new method and new parameter
* `folksonomy.dart`: new `getValues` method; new optional parameter for `getKeys`
* `openfoodfacts.dart`: added new `value_count.dart` file
* `pubspec.yaml`: downgraded to working version numbers

feat: 1104 - folksonomy "getValues"

---

lib/src/model/product.dart
lib/src/model/product.g.dart
lib/src/utils/product_fields.dart
lib/src/utils/product_query_configurations.dart
test/api_get_product_test.dart

- Now we can use decimal API versions - e.g. `3.2` - instead of just `int`
- New related product field `schemaVersion`
- #1055
* `api_get_product_test.dart`: added a test about API versions matching schema versions
* `product.dart`: new field `schemaVersion`
* `product_fields.dart`: new product field `SCHEMA_VERSION`
* `product_query_configurations.dart`: now the version number can be decimal

feat: 1055 - API versions as decimal, Product.schemaVersion
